### ISSUE TITLE
IR NECext

### ISSUE THREAD

**Issue by Kyvyw** [BruceDevices/firmware#110]
Hello,
I see that in the PR #80 that the NECext protocol have been removed?
Why?
Thank you.

**Comment by bmorcelli** [comment]
Because the code was the same as NEC

**Comment by Kyvyw** [comment]
okay, but in this case just add that if its NECExt it just do the same as NEC, because now I need to edit all my files..

**Comment by bmorcelli** [comment]
https://github.com/pr3y/Bruce/blob/b01fd76a4e3d0bb2284480fffa4794a80d174e71/src/modules/ir/TV-B-Gone.cpp#L420

If the protocol starts with NEC, it will send..

So you don't need to change anything
