### ISSUE TITLE
Feature Suggestion : Deauth channel hopping..........+more

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#120]
Finally the settings will be saved. 
I flashed the firmware and it was way better than the previous one.

v1.3 easily makes this the best firmware for the m5stick.

I just got these ideas that I think will help:

* Moving the "set time" functions of the clock to the "Config".
* Clicking the clock icon displays the time. Without needing be reminded of the time every time it's been clicked.
* The pause function on custom ir is great. It'll be better if it can be resumed too.
* Making that raw sniffer to work without SD card (If possible).
* Making the mic graph faster. 
* Bluetooth DDoS attack.
* BLE badusb. (you can study the code from the portal.hack demo firmware).

**Comment by eadmaster** [comment]
suggestion for more mic graphs here
https://github.com/pr3y/Bruce/issues/125

> BLE badusb. (you can study the code from the portal.hack demo firmware).

Isn't that closed source?

**Comment by Z-SHOCK-E** [comment]
Hmm... Unfortunately yes.

But it shouldn't be that hard. The cardputer demo firmware has a ble keyboard. That code can be used too.

**Comment by Z-SHOCK-E** [comment]
Rescanning while deauth attack to detect channel hopping.

**Comment by Z-SHOCK-E** [comment]
The mic graph on the demo updated way faster. It'll be nice to have it with Bruce too.
