### ISSUE TITLE
RF Scan/Copy  wont work

### ISSUE THREAD

**Issue by delmarado** [BruceDevices/firmware#121]
I was trying to test the new function Scan/Copy in the RF section but it wont work i have the rf433r unit plugged in but it wont read any rf signal, i dont know if im the only one having this issue. Thanks in advance for your great work.

**Comment by bmorcelli** [comment]
Theres the possibility of your emitter is using FSK (Frequency Shift Modulation) to send the codes..

You will see things on the spectrum, but there will be no On Off Keying received by the RF433R to be processed, since M5 modules work only on ASK/OOK (Amplitude Shift Keying) /On Off Keying)
