### ISSUE TITLE
station deauther?

### ISSUE THREAD

**Issue by jkrowtheh4cker** [BruceDevices/firmware#122]
could you make it able to deauth both APs and stations, like @spacehuhns deauther?

**Comment by bmorcelli** [comment]
Roadmap:
- [x] before start deauth, scan for the AP and save bssid and channel (as done in deauth flood)
- [x] after scanning, enter in promiscuous mode and sniff for packets to make a list of Stations connected to each AP. Inside packet macTo are after byte 16 and macFrom after byte 22 of the packet (check both macs for AP and save the other in a list, take care to not duplicate)
- [x] hop from channel to channel and spaming addressed deauth frames along with broadcast.


Add option on deauth flood to choose APs or spam to all.

**Comment by jkrowtheh4cker** [comment]
thanks!
