### ISSUE TITLE
Hi 👋

### ISSUE THREAD

**Issue by LEGOATDU49** [BruceDevices/firmware#155]
Hi, I have a question that has nothing to do with the m5launcher but would it be possible for you to program me a firmware for m5stickcplus2 for free. 

And just to tell you, you can solve the problem on the Megaolodn games on the bruce frimware, we can only go down but nothing happens when we go up.

Thanks😁

**Comment by Lamnxzp** [comment]
Hello, 
The up movement was fixed here #152
