### ISSUE TITLE
deauth not workning

### ISSUE THREAD

**Issue by NyanTyans** [BruceDevices/firmware#157]
HI in 1.3.1 deauth not working, at 1.3 working fine.

**Comment by NyanTyans** [comment]
m5 stick c plus 1

**Comment by jkrowtheh4cker** [comment]
same... don't know why. do you know how to get back to 1.3 after you install 1.3.1?

**Comment by bmorcelli** [comment]
it was fixed here https://github.com/pr3y/Bruce/pull/151

will be available in he next update
