### ISSUE TITLE
Bluthoot death

### ISSUE THREAD

**Issue by LEGOATDU49** [BruceDevices/firmware#161]
a bluethoot deauth plz

**Comment by IncursioHack** [comment]
When opening an issue to people, I suggest that they research beforehand about possible implementations, some example code for ESP32/Arduino or bring insights into the real use of the mentioned feature.

This makes it easier to understand what you really want and what we can develop within our time and knowledge limitations.

If it is an informal request from the point of view of curiosity, I suggest debating the topic on Discord.
