### ISSUE TITLE
[Bug Report]  Evil Portal Custom returns to Bruce's main menu.

### ISSUE THREAD

**Issue by IncursioHack** [BruceDevices/firmware#163]
[Test Bruce] 1.3.1  /248 - Dev -  https://github.com/pr3y/Bruce/actions/runs/10332927025
[Version/Artifact] Bruce_m5stack-cardputer_248
[Datetime] 08/10/2024 - 13:30 [GMT-3]
[Device] Cardputer

[Bug Report]

Evil Portal
When selecting WIFI > Evil Portal > Custom HTML and selecting any HTML it returns to Bruce's main menu.

[13:43:09]Selecionado Evil Portal
[13:43:10]Selecionado Custom Html
[13:43:11]Selecionado SD Card
[13:43:19]
Preparing deauth frame to -> 0:0:0:0:0:0Error changing channel

**Comment by bmorcelli** [comment]
https://github.com/bmorcelli/Bruce/blob/1e16cb640eb107b1ae2e08bcd6cd2759d5cdde41/src/core/sd_functions.cpp#L437 : when choosing file, loopSd is switching "returnToMenu" to true to ensure screen redraw at main Menu..

It can be done elsewhere, and taken from here to fix this problem
