### ISSUE TITLE
[Bug Report] Small visual bug on Bruce's Clock where the seconds appear below.

### ISSUE THREAD

**Issue by IncursioHack** [BruceDevices/firmware#171]
[Test Bruce] 1.3.1 /248 - Dev - https://github.com/pr3y/Bruce/actions/runs/10332927025
[Version/Artifact] Bruce_m5stack-cardputer_248
[Datetime] 08/10/2024 - 16:15 [GMT-3]
[Device] Cardputer

[Bug Report]
Clock

When selecting the Clock, it displays the second fret of the second in the bottom row.

![Clock - IncursioHack](https://github.com/user-attachments/assets/8064ec0f-a506-4e2c-b829-31ec3e79975b)

**Comment by bmorcelli** [comment]
At line https://github.com/pr3y/Bruce/blob/b9fa9369f911e38537815bb244fa55d3e48b7d39/src/core/settings.cpp#L541

Use this:
` tft.drawCentreString(timeStr,WIDTH/2,HEIGHT/2-13,1); `

**Comment by IncursioHack** [comment]
[Test Bruce] 1.3.1 /254 - Dev - https://github.com/pr3y/Bruce/actions/runs/10342227214
[Version/Artifact] Bruce_m5stack-cardputer_254
[Datetime] 08/12/2024 - 06:55 [GMT-3]
[Device] Cardputer

The bug has been fixed in the version mentioned above.

I thank you for your commitment @bmorcelli , you are amazing as always.
