### ISSUE TITLE
IR Read won't write the file to little fs. (Bug)

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#173]
On the stick c plus2 I built and flashed the firmware from pio via vs code. Ir read works ok with a 3 pin ir sensor but it won't save anything. Insted of writing the file to littleFS it gives an error. I even tried it after creating a folder named "BruceIR" but still no luck.

**Comment by Lamnxzp** [comment]
https://github.com/pr3y/Bruce/blob/038da5a64167ca8a1ba5475799edc2ebbfdae8e7/src/modules/ir/ir_read.cpp?plain=1#L177
Maybe by changing this to
```cpp
if(checkLittleFsSize()) fs=&LittleFS;
```

will work?

**Comment by Z-SHOCK-E** [comment]
Thanks it worked. Sorry for the late reply.
