### ISSUE TITLE
AI?

### ISSUE THREAD

**Issue by jkrowtheh4cker** [BruceDevices/firmware#178]
could we add an AI chatbot like the cardputer Gemini that @vanshksingh made
just a thought

**Comment by vanshksingh** [comment]
Interesting, I mean I can make a pull request to this project with that added would that be cool ?

**Comment by bmorcelli** [comment]
I don't think it adds something to the project scope..

If it comes to bruce, Can be set as a optional feature for those who wants it.. but I fear it'll fill out IRAM table that could be used to a more valuable thing

**Comment by jkrowtheh4cker** [comment]
yeah... I forgot about limited IRAM
do you think that the next update will fix the deauther problem / add more deauther features

**Comment by bmorcelli** [comment]
I fixed it in the https://github.com/pr3y/Bruce/pull/176

Deauth Flood I couldn't test it it deauths or not, but I could capture the packets 


Station Deauth I didn't have time to make yet.. maybe next month I'll have time for that

**Comment by jkrowtheh4cker** [comment]
I noticed that on m5launcher/m5burner you can't get the new 1.3.1 with fixes.
do you know why this might be happening?

**Comment by bmorcelli** [comment]
It wasn't posted there, probably..

**Comment by jkrowtheh4cker** [comment]
I think it might work if you post it to m5launcher/m5burner as 1.3.2 so it won't install the old version
