### ISSUE TITLE
Mic

### ISSUE THREAD

**Issue by LEGOATDU49** [BruceDevices/firmware#184]
Can you add the microphone from the demo version but from the stickc plus 2, I find it better. Or when we go to mic spectrum on. could choose the version.      And the custom Ir works for which TV for the m5stickc plus 2?

**Comment by IncursioHack** [comment]
There is a list of Infrared that can be used, there are several models and brands of TV. See the Wiki.
I suggest bringing some of these issues on Discord so we can discuss it before it becomes an issue.

https://github.com/pr3y/Bruce/wiki/IR

**Comment by bmorcelli** [comment]
Related to https://github.com/pr3y/Bruce/issues/125
