### ISSUE TITLE
[Feature Request] Icon Fix

### ISSUE THREAD

**Issue by alsoduck** [BruceDevices/firmware#187]
some blank pixel found in BLE icon.
RF icon position too close to status bar.

Maybe google material icon can help

**Comment by IncursioHack** [comment]
As it is something visual, could you send some photos to exemplify what you just commented? Also, what conditions are we talking about? (example: when you connect to WIFI and then connect to Bluetooth)

**Comment by bmorcelli** [comment]
Icons are hardcoded to save flash memory and to work with different color schemes..

Sometimes display doesn't render all pixels properly and display a few white pixels
