### ISSUE TITLE
Build Error on Windows

### ISSUE THREAD

**Issue by Lamnxzp** [BruceDevices/firmware#197]
**Describe the bug:**
Since this change:
https://github.com/pr3y/Bruce/blob/c207220edda59ba96b59879f0580ba12458f0431/platformio.ini#L35

The build seems to fail on Windows OS.

**Steps To Reproduce:**
- Clone the repository (c207220edda59ba96b59879f0580ba12458f0431)
- Install platformio using pip: `pip install platformio`
- Build the firmware (ex: for stickc plus2): `pio run -e m5stack-cplus2`
- Observe the build process failing during compilation.

- Device used: Windows 11 23H2

**Comment by bmorcelli** [comment]
Thank you for the detailed explanation..

I just fixed and merged the fix!
