### ISSUE TITLE
Add this QR code

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#201]
Please add this to the qrcode function and name it "Reaper"

DONT OPEN THIS LINK : https://jonnybanana.github.io/safari-ie-reaper.github.io/

Plz add this link it makes some web browsers freeze.

**Comment by eadmaster** [comment]
with this, you can generate qr codes from any small file directly from the file manager https://github.com/pr3y/Bruce/pull/196

**Comment by Z-SHOCK-E** [comment]
Ok thanks.
