### ISSUE TITLE
Scan Hosts wont work on the m5stickc plus 2

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#203]
Scan host will just go back to main menu even after connecting to wifi.

**Comment by bmorcelli** [comment]
https://github.com/pr3y/Bruce/commit/4312ca2ffa3dea37e415ff6e3d2a05c72dcc9553 fixed here now.. 

Try this binary https://github.com/pr3y/Bruce/actions/runs/10494104975/artifacts/1838504248
