### ISSUE TITLE
Config is missing. Just compiled the latest version.

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#205]
I just compiled the latest version of bruce for the m5stickc plus 2. After that I noticed that the config tile is gone. How can I change the brightness and other settings.

**Comment by bmorcelli** [comment]
It was renamed to bruce.conf
Check on littleFs, maybe the SdCard wasn't mounted well

**Comment by Z-SHOCK-E** [comment]
No no. I mean the Config tile in the bruce main menu. On the m5stickc plus 2. It's gone.

**Comment by bmorcelli** [comment]
Indeed, FM Radio menu was added, increasing the number of options, and the number of options wasn't updated on the loop function, so it was jumping ip.

I fixed it now, the new bin will be available in 2 minutes

**Comment by bmorcelli** [comment]
https://github.com/pr3y/Bruce/actions/runs/10493912186/artifacts/1838445730

**Comment by Z-SHOCK-E** [comment]
Ok. Can you plz show me what was causing it to dissapear.

**Comment by bmorcelli** [comment]
https://github.com/pr3y/Bruce/commit/2cc9a9820e7c365c2f3c4382fd79ba1020ef572a

**Comment by Z-SHOCK-E** [comment]
Ah ok. Thanks
