### ISSUE TITLE
LoRaE220-433

### ISSUE THREAD

**Issue by Jawen33** [BruceDevices/firmware#206]
Hi, can you let me know how ton use this dongle please ?
Thanks a lot.

**Comment by IncursioHack** [comment]
@Jawen33 
Please join Bruce's group:
https://discord.gg/5wVDS4zx

Or in the Cardputer Group:
https://discord.gg/Mjtxmeyu

We leave this space reserved to deal with bugs in the firmware and new implementations. In the groups I mentioned you should be able to get some answers and even more information.
