### ISSUE TITLE
Cardputer Lockscreen

### ISSUE THREAD

**Issue by FernandoJose2** [BruceDevices/firmware#222]
It would have been nice to have the ability to lock the screen every time Bruce runs something, say a deauth flood or a raw sniffer, so that random taps wouldn't stop those attacks when you run your cardputer in your pocket.

**Comment by bmorcelli** [comment]
It already waits for Esc key to be pressed, all the other keys are "supressed" at these moments, I don't see a reason to change it..

It is easier for you to print a cover to it than add an other useless security level for undesired key press
