### ISSUE TITLE
Nrf24 diagram ans Enhance Mic Spectrum

### ISSUE THREAD

**Issue by MrFlit** [BruceDevices/firmware#223]
**Hi.** I have some ideas for improving the project that you might like.:
1) **NRF24L01**
It would be nice to add a detailed connection diagram NRF24L01 for M5stack Plus 2 and 1 in README.md
Since the link to the `CC1101` connection may mislead new users. Or [here](https://github.com/pr3y/Bruce/wiki/BLE#NRF24-Jammer)
2) **Improvement for Mic Spectrum**
Add a choice between your mic spectrum and what was done in the initial example when launching M5stack Plus. 
3) **Sound noise** 
Emit an annoying sound, which could be used to disrupt or any people nearby. May have applications in pranks or as a deterrent in certain situations. You can also use `HAT-SPK2` and play sounds from an `SD card`.

**Comment by metecicek** [comment]
You can use these sound effects for prank.

https://github.com/metecicek/Bruce/tree/main/sd_files/sound_noise

**Comment by MrFlit** [comment]
Thx
