### ISSUE TITLE
Why are .BIN files always displayed in readFs?

### ISSUE THREAD

**Issue by Lamnxzp** [BruceDevices/firmware#234]
Hello,

In the `readFs` function used in `loopSD`, I noticed that .bin files are **always** displayed in the list of files to select, even if the `allowed_ext` is set to (for exemple) `WAV`.
https://github.com/pr3y/Bruce/blob/e79ab19e273619237968244b142caea249dd639f/src/core/sd_functions.cpp#L492-L497

Is there a specific reason for this?

Thank you.

**Comment by bmorcelli** [comment]
No, this is something that must be fixed.

**Comment by Lamnxzp** [comment]
Okay thank you, I will make a pull request then..
