### ISSUE TITLE
RF: Separate and emit 433 signals of the file, when there are more than 1

### ISSUE THREAD

**Issue by loni1488** [BruceDevices/firmware#235]
Hello Bruce!
I would like to advise a new introduction, but I don't know at all if it can be added, in general, do the same as flipper zero selection for opening gates, slagbaums and the rest

**Comment by IncursioHack** [comment]
Bruce can load SubGhz files, the same ones used in Flipper, it is compatible with the vast majority, as long as the correct module is connected and properly configured. Take a look at the Wiki.

https://github.com/pr3y/Bruce/wiki/RF

https://github.com/pr3y/Bruce/wiki/CC1101

**Comment by loni1488** [comment]
No, I mean, emit signals by the method of picking, how tv-b-gon
