### ISSUE TITLE
Rfid error

### ISSUE THREAD

**Issue by LEGOATDU49** [BruceDevices/firmware#238]
When I read my badge and I want to put it in a blank it gives me an error

I read the badge, then I go to write and it gives me an error

**Comment by IncursioHack** [comment]
What is the frequency of the card, 13.56 Mhz or 125 Khz?

What type of modulation, 14443A or other?

Are you using the M5Stack RFID2 or the PN532?

Is the card you are using a rewritable model with Block 0 UID?

When it comes to RFID there is a universe of situations, check them all.

**Comment by LEGOATDU49** [comment]
13,56mhz
14443A
M5stack RFID2

**Comment by IncursioHack** [comment]
> 13,56mhz 14443A M5stack RFID2

Is the card a Block 0 UID model? Several "blank" cards do not allow changing the UID (card identifier) ​​unless it has the "Block 0 UID" information.
https://s.click.aliexpress.com/e/_Ddm7lYX

**Comment by LEGOATDU49** [comment]
Oui, c'est le bloc 0

**Comment by LEGOATDU49** [comment]
Yes its a block 0 uid

**Comment by IncursioHack** [comment]
If your card is indeed Block 0 UID, please test it with one of the versions below:

StickC 2: https://github.com/pr3y/Bruce/actions/runs/10670832460/artifacts/1883071277
StickC 1.1: https://github.com/pr3y/Bruce/actions/runs/10670832460/artifacts/1883070856
Cardputer: https://github.com/pr3y/Bruce/actions/runs/10670832460/artifacts/1883071508

**Comment by LEGOATDU49** [comment]
Okay I'll test

**Comment by LEGOATDU49** [comment]
I only need the write function for the blank card to work or I also need to use clone uid

**Comment by rennancockles** [comment]
Can you give some more details?

Are you reading from a card and trying to write into another?
When you read the first card what type is displayed in the device? (NTAG21x, MIFARE 1k, ...)
When you read the second card what type is displayed in the device? (NTAG21x, MIFARE 1k, ...)
Do you want to clone the card (make both work as the same one) or just copy the data?

**Comment by LEGOATDU49** [comment]
1 yes
2 Mifare 1K
3. Mifare 1k
4 Clone

**Comment by rennancockles** [comment]
Okay, so after reading the first tag you have to press OK and select "Clone UID". If you still get an error so your tag is probably not good for writing into block 0.

**Comment by LEGOATDU49** [comment]
Ah okay
