### ISSUE TITLE
Bruce WebUI is unusable. ( Latest Version )

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#255]
So I compiled and uploaded the new bruce firmware to my m5stick c plus 2 and I was trying to access the web ui to upload some .ir files. It asks for username and password after providing the correct creds it'll load continiously. I tried clearing browser cache & cookies but still no luck.

**Comment by bmorcelli** [comment]
How many files do you have in the root of your SD card?

Edit: and folders

**Comment by Z-SHOCK-E** [comment]
Well, I don't use a sd card because I only need to store a few .ir files. I use the LittleFS for that.

**Comment by bmorcelli** [comment]
I am refactoring a few things here, and webui is one of them

**Comment by Z-SHOCK-E** [comment]
Ok. Thanks

**Comment by bmorcelli** [comment]
will be treated in this issue: https://github.com/pr3y/Bruce/issues/246
