### ISSUE TITLE
CC1101 doesn't work on M5sticksCplus2

### ISSUE THREAD

**Issue by TheBlueRunner** [BruceDevices/firmware#256]
Hello, im testing bruce firmaware 1.5 on a M5stickCplus2 with a CC1101 and the cables are good, I set the rf module on CC1101 and when i try to copy or the spectrum it doesn't work, idk if it's a bug or something else, idk how to solve this please help me 🙏

**Comment by GoldenboyITA** [comment]
Try to open spectrum and remove SD card.

**Comment by TheBlueRunner** [comment]
> Try to open spectrum and remove SD card.

I didnt put a sd card, I only put the CC1101

**Comment by bmorcelli** [comment]
well.. I tested it here and it works... check your wirings and module..

people can help you on out discord group.
