### ISSUE TITLE
show scripts in a separate menu (plugins-like)

### ISSUE THREAD

**Issue by eadmaster** [BruceDevices/firmware#258]
to quickly access [js scripts](https://github.com/pr3y/Bruce/wiki/Interpreter), i've added a top-level menu auto-populated with the js scripts files inside the "/scripts" folder:

![scripts](https://github.com/user-attachments/assets/19c08a1b-3564-4093-8132-5d3c2298c3c8)

If the "/scripts" folder is missing, the menu only shows the "Load..." entry to manually  pick a script file from storage.

Currently i am only missing an icon for the new menu.

**Comment by eadmaster** [comment]
added in [v1.6](https://github.com/pr3y/Bruce/releases/tag/1.6).

@rennancockles : thanks for the [new icon](https://github.com/pr3y/Bruce/commit/e47b5a9c288d9128a54e260bc00e8f63ad627ae8)!

**Comment by shubtheone** [comment]
how to upload the js files in m5stick? I cant do it

**Comment by Wyattbro132** [comment]
How can I use a Wi-Fi AP to transfer files?

**Comment by bmorcelli** [comment]
> How can I use a Wi-Fi AP to transfer files? 

https://youtu.be/SIYZ7XNIM9o
