### ISSUE TITLE
Custom Boot Image for M5stickC Plus 1.1 

### ISSUE THREAD

**Issue by logm1lo** [BruceDevices/firmware#262]
**Is your feature request related to a problem? Please describe.**
I would love to add an option or a wiki for adding custom images when booting up. 
I would like to use some of your artwork. I've seen other developers do it on the M5stickC Plus 1.1 so I wouldn't see this as a problem when implementing it to this firmware too.

**Comment by bmorcelli** [comment]
It is almost done.. 

I'm wrapping up the code and polishing some bytes here

**Comment by bmorcelli** [comment]
done here: https://github.com/pr3y/Bruce/pull/273
