### ISSUE TITLE
Bad usb error

### ISSUE THREAD

**Issue by cinouw** [BruceDevices/firmware#267]
Hi
so I tried to run this ducky script
[payload.txt](https://github.com/user-attachments/files/17007731/payload.txt)
and I am always getting this error saying that LEFT_ARROW not spported running as STRINGLN

**Comment by bmorcelli** [comment]
https://github.com/pr3y/Bruce/blob/7a8850c29f8c5b7790f446578335580aa5675522/src/modules/others/bad_usb.cpp#L125

Fix your script, there's no "_" in the command.


Use LEFT of LEFTARROW

**Comment by cinouw** [comment]
Thanks for the help appreciate it
