### ISSUE TITLE
BLE doesn't work well.

### ISSUE THREAD

**Issue by Zernic** [BruceDevices/firmware#27]
Ble works its just very very slow like applejuice and sourapple is just slow before something pops up. (Im using ios btw)

**Comment by pr3y** [comment]
BLE spam needs to have a delay to work nowadays, on previous versions of Bruce it was possible to spam applejuice packet 200 times per second and it just dont work like that, read every source of BLE spam has a adv_delay, also dont spam issues pls

**Comment by Zernic** [comment]
Oh sorry I was just trying to help as I saw this was kinda new.
