### ISSUE TITLE
Nrf24 bug i think

### ISSUE THREAD

**Issue by cinouw** [BruceDevices/firmware#271]
Hi Bruce team

So i don't know if this is bug or a feature  but the nrf24 jammer in the bluetooth menu is jamming 2.4ghz wifi signals instead of bluetooth 😅

**Comment by bmorcelli** [comment]
It is not a bug.. that is why the nrf24 jamming is in Wifi and ble options..

**Comment by cinouw** [comment]
But it is only jamming wifi signals bluetooth signals doesn't semm to be affected at all

**Comment by bmorcelli** [comment]
It will jamm 2.4ghz signals, 5ghz bluetooth won't be affected..

And if the Bluetooth source and client (smartphone and ble speaker) are close to each other, ot will be harder to jam, because the signal between them can be stronger than nrf signal

**Comment by cinouw** [comment]
Okey now i get it thank you so much
