### ISSUE TITLE
Bluetooth badusb 

### ISSUE THREAD

**Issue by sousaaguilherme** [BruceDevices/firmware#276]
It would be great if the badusb could be done through Bluetooth. I haven't tested, but I think there is a firmware named badcard that supports this, so does flipper zero

Thanks!

**Comment by bmorcelli** [comment]
Being discussed in this issue https://github.com/pr3y/Bruce/issues/239

**Comment by sousaaguilherme** [comment]
I'm not sure it's the same thing. In that issue they're talking about Bluetooth vulnerabilities, and what I was asking for was executing rubber ducky scripts with Bluetooth emulated keyboard instead of connecting the cardputer through usb
