### ISSUE TITLE
Battery isn't accurate. 

### ISSUE THREAD

**Issue by Zernic** [BruceDevices/firmware#28]
The battery isn't accurate when scrolling or changing something on the screen the battery will randomly go up or down and sometimes it can be drastic it said it was at 50 then i changed into a page and it said 83.

**Comment by pr3y** [comment]
this depends on your battery health, you probably used it while recharging and this implicated on your battery

**Comment by Zernic** [comment]
No I actually just got the thing it just came in the mail.
