### ISSUE TITLE
Cant scan/copy RF with CC1101

### ISSUE THREAD

**Issue by sousaaguilherme** [BruceDevices/firmware#286]
I'm using a CC1101, and can see its working with spectrum.

However, when scan/copy is chosen and I press a button on a RF remote, it nevers captures it; it always says "Waiting for signal. Ready, waiting".

Am I doing something wrong or is it a bug?

Thank you for your work :)

**Comment by detcord0** [comment]
May be it doesnt support your key.try with cheap remote and see it work or not.

**Comment by bmorcelli** [comment]
Bruce works with ASK/OOK modulation for now... FSK will be implemented in the future... probably this is the case..

In version 1.6 it is scanning the frequencies with cc1101, so you can test it for different frequencies
