### ISSUE TITLE
Add a packet of IR signals

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#291]
Make tv b gone for projectors

**Comment by metecicek** [comment]
You can use these packages for television, projector, sound, air conditioner, fans. Everything you want is available in the links below.

https://github.com/flipperdevices/flipperzero-firmware/tree/dev/applications/main/infrared/resources/infrared/assets

https://github.com/UberGuidoZ/Flipper/tree/main/Infrared
