### ISSUE TITLE
No SD-card found on core2

### ISSUE THREAD

**Issue by loewal** [BruceDevices/firmware#297]
**Describe the bug:**
sd-card not recognised;even tried in Webui to create a directory: "Nothing in here, sharky!"???

**Steps To Reproduce:**
Start WebUI
- Device used: 
M5stack Core2
**Expected behavior:**
Existing sd-card

**Actual behavior:**
Already described

Used a Fat32 formatted card; tried on Pc: ok

**Comment by bmorcelli** [comment]
Is it SDHC or SDXC?

**Comment by bmorcelli** [comment]
Fixed on Beta https://github.com/pr3y/Bruce/pull/309
install with the Web flasher at: https://bruce.computer

SD Card must be SDHC, lesser than 32Gb, the cheaper the better..
