### ISSUE TITLE
how to add custom IR

### ISSUE THREAD

**Issue by AzhariRamadhan** [BruceDevices/firmware#30]
can you give me some example code or anything about custom IR

**Comment by Lamnxzp** [comment]
Use the [WebUI](https://github.com/pr3y/Bruce/wiki/Others#webui)

**Comment by bmorcelli** [comment]
It work with these .ir files
https://github.com/Lucaslhm/Flipper-IRDB

**Comment by AzhariRamadhan** [comment]
> It work with these .ir files https://github.com/Lucaslhm/Flipper-IRDB

not work at all

**Comment by bmorcelli** [comment]
You are right.. it is working with raw data protocols.. Samsung codes and some others are not working..

If you test the TCL tv codes you will that they are working.


I'm working on a fix for this..

Thank you!
