### ISSUE TITLE
Noise sound from device

### ISSUE THREAD

**Issue by alsoduck** [BruceDevices/firmware#303]
**Describe the bug:**

There is noise when device is turned on.
**Steps To Reproduce:**

- Device used: M5StickCPlus2
1. Turn on the device.
2. Listen carefully to the device and you hear noise. If connected to USB, you can easily hear the noise.
**Expected behavior:**

no noise.
**Actual behavior:**

noise exists.
**Additional context / logs:**

maybe something is wrong with buzzer pin

**Comment by bmorcelli** [comment]
I don't have this issue here..

try the beta version, and disable the Boot sound "Config> Sound On/Off"
