### ISSUE TITLE
Flipper like JS format

### ISSUE THREAD

**Issue by MegaTheLEGEND** [BruceDevices/firmware#305]
**Describe the solution you'd like**

It would be Cool if the JS interpreter followed the same format as that of the Flipper.

**Additional context**

instead of this
```
wifiConnect(ssid : string);

dialogError(msg : string);
```

it would be like this
```
let math = require("math");  // math modual would be cool. (maybe it already exists?)
let badusb = require("badusb");
let wifi = require("wifi");
let dialog = require("dialog");

math.abs(-5); // 5
badusb.setup();


if (badusb.isConnected()) {
    badusb.press("E");
} else {
   dialog.error("failed to connect badusb"); //  Show an error
}

wifi.connect(ssid : string);
```

This provides a more organized method of calling functions and also would increase possible interoperability between Bruce and Flipper scripts

https://github.com/flipperdevices/flipperzero-firmware/tree/dev/documentation/js

**Comment by pr3y** [comment]
This is already implemented in the firmware.
Read here https://github.com/pr3y/Bruce/wiki/Interpreter

**Comment by eadmaster** [comment]
i've investigated this a bit already, it needs [this optional extra module](https://github.com/joeqread/arduino-duktape/tree/main/extras/module-node).

**Comment by MegaTheLEGEND** [comment]
That would be cool. Also I feel like it would be great if users could share their js apps on a catalog on the website. A lot of times the most innovative and creative ideas come from the users and community.

**Comment by pr3y** [comment]
Loved this idea! this will probably be added soon!
For now, there is a channel where people can share apps on our official Discord, [here](https://discord.com/channels/1264994142769909854/1292085353808920616) or in the [projects thread](https://discord.com/channels/1264994142769909854/1292088941843054753)
