### ISSUE TITLE
Random Mistake

### ISSUE THREAD

**Issue by jkrowtheh4cker** [BruceDevices/firmware#313]
this doesn't matter at all, but for some reason on https://bruce.computer BLE beacon is spelt as BLE bacon, also, I read the docs, but I don't quite understand what the radio hijacking tool is supposed to do, thanks.

**Comment by IncursioHack** [comment]
@jkrowtheh4cker The radio hijacking feature was not implemented, it is in the documentation as a reference to the code created by @valentin8709 .
