### ISSUE TITLE
Bad BLE - Incorrect characters (in PT-PT layout at least)

### ISSUE THREAD

**Issue by sousaaguilherme** [BruceDevices/firmware#317]
Bad BLE, at least in PT-PT layout is typing incorrect chars.

## Example script:
```
DELAY 300
STRING !"#$%&/()=?>
ENTER
DELAY 30
STRING \1234567890'<
DELAY 30
ENTER
STRING p+
DELAY 30
ENTER
STRING P*
DELAY 30
ENTER
STRING ,.-
DELAY 30
ENTER
STRING ;:_
DELAY 30
ENTER
STRING @{[]}
DELAY 30
ENTER
STRING END
ENTER
```

## Result:
```
!"#$%&/()=?^
\1234567890'~
p+
P*
,.-
;:_
>END

```

## Expected:
```
!"#$%&/()=?>
\1234567890'<
p+
P*
,.-
;:_
@{[]}
END

```

**Comment by sousaaguilherme** [comment]
The new version fixed the issue! Thanks for merging @bmorcelli !

**Comment by bmorcelli** [comment]
you are welcome!!

and btw.. we were so happy about this issue!! it should be put on a portrait and shown to everybody! very organized and pointing the errors clearly! Congratulations!

**Comment by softm5** [comment]
Bonjour, 
J'ai aussi un problème similaire avec la derniere version de "Bruce"
Lorsque lance mon payload badBLE avec clavier AZERTY FR,  J'ai  en résultat : 
("chrome "https://www.youtube.com/@€#")
Alors que normalement ça doit écrire ceci : ("chrome "https://www.youtube.com/@test")
