### ISSUE TITLE
Keyboard_2b wont pair with my M5StickC Plus 2

### ISSUE THREAD

**Issue by AnmeldungsFehler** [BruceDevices/firmware#319]
Hi,

so yesterday i tried the new "Media Cmds" function on my StickC plus 2, it worked perfectly fine. Today i wanted to test something out but the "keyboard_2b" wont pair with my StickC plus 2.
Are there suggestions on how to fix that bug/ is it even a bug ?

Edit: I went to Bad BLE chose a keyboard layout and tried to connect to the keyboard again, it worked, BUT i cant take a screenshot, cant turn the volume op or down or mute the device. The screen of the m5stick flickers just a bit, thats all.

With best regards,
AnmeldungsFehler

**Comment by IncursioHack** [comment]
Try clearing the device from your smartphone's Bluetooth list and connect again.
