### ISSUE TITLE
Problème BadBLE Caractère

### ISSUE THREAD

**Issue by ghost** [BruceDevices/firmware#322]
Bonjour,
J'ai un problème avec la dernière version de "Bruce"
J'ai des caractères incorrect, lors de l'utilisation de BadBLE.
Exemple de mon payload : 
(chrome "https://www.youtube.com/@test")

Résultats incorrect:
("chrome https://www.youtube.com/@%#")

Je suis en "AZERTY FR"

**Comment by bmorcelli** [comment]
problem is in the BleKeyboard::release(uint8_t k) function
