### ISSUE TITLE
Target Deauth attack info is no properly fit on the m5stickc plus 2. I increased the deauth pkt rate btw.

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#330]
Some info on the left side are out of the display.

**Comment by IncursioHack** [comment]
Could you give us more details about what is happening? If possible, record a video and bring data from Serial communication.

**Comment by Z-SHOCK-E** [comment]
Sorry for the late reply .It is solved in the latest version.
