### ISSUE TITLE
CYD-2432S028 UI colors inverted??

### ISSUE THREAD

**Issue by flaryx32** [BruceDevices/firmware#331]
**Describe the bug:**

Ui colors are inverted: background color is white and borders/icons and text is green?

**Steps To Reproduce:**

just flashed from webflasher and was like this.
- Device used: 
CYD-2432S028

**Expected behavior:**
Black background and purple colors for borders, icons and text

**Comment by bmorcelli** [comment]
Your board might be the **2USB variant (but without the other USB port)**..

Install the 2USB version.. it might do the trick ;-)
