### ISSUE TITLE
I need connection scheme

### ISSUE THREAD

**Issue by Sonys9** [BruceDevices/firmware#343]
can you give me a scheme for RC-522 to m5stickc plus2? (not via discord, discord is banned in my country)

**Comment by Sonys9** [comment]
![image](https://github.com/user-attachments/assets/2c0825f7-8162-4fd5-9fac-9c9d7096dc24)

**Comment by rennancockles** [comment]
![RC522-RFID-Reader-Writer-Module-Pinout](https://github.com/user-attachments/assets/9da09163-0594-4a96-98e7-eba1e5e89d87)

Use I2C connection (SDA SCL GND 3.3V) and connect to grove port like this

![pn532_i2c](https://github.com/user-attachments/assets/aa8aad97-b9da-4a6b-84f7-27a64046e8f0)

**Comment by rennancockles** [comment]
![RC522-RFID-Reader-Writer-Module-Pinout](https://github.com/user-attachments/assets/5bb2c013-41a4-47ac-87a7-21b8e66365a3)

Use the I2C connection (SDA SCL GND VCC)

**Comment by rennancockles** [comment]
Be careful that RC522 uses 3.3V and grove port outputs 5V. You need to use the 3.3V from stickc plus2 gpio

**Comment by Sonys9** [comment]
![image](https://github.com/user-attachments/assets/7fae378c-797d-442c-8d91-12722d2c7952)

**Comment by Sonys9** [comment]
![image](https://github.com/user-attachments/assets/781afa3a-f399-4722-a520-7499496135e0)
