### ISSUE TITLE
Not working after building source and flashing

### ISSUE THREAD

**Issue by kerneltech1488** [BruceDevices/firmware#348]
I have M5StickC PLUS2. I've built firmware and flashed it. Nothing works. When I flash the .bin from releases, it works. I don't know what could be the problem.

**Comment by IncursioHack** [comment]
@kerneltech1488 
We will not be able to support your software development application. It is recommended that you check the folders, libraries and compile following what was indicated in our documentation. I also didn't find a fork of our system on your Github.
The documentation can be found here:
https://github.com/pr3y/Bruce/wiki

To record Bruce on your device, try here:
https://bruce.computer/
