### ISSUE TITLE
breathalyzer support

### ISSUE THREAD

**Issue by Sonys9** [BruceDevices/firmware#349]
I wanna a breathalyzer support in Bruce firmware. 
I think its a very good feature, because you can add alcohol testing before each use of any function to reduce the chance of illegal cyber attacks while intoxicated.

**Comment by yousmellstupidhaha** [comment]
💀

**Comment by Jethro-San** [comment]
This is a joke, right...

**Comment by TheMiner203** [comment]
As a Russian, I agree. I had a situation where, after three bottles of Russian vodka, I sat on a bear and went to hack the Pentagon using m5stick. Then the police caught me and forced me to sell the balalaika and pay a fine. If Bruce had a breathalyzer function, this wouldn't have happened. Please add a forced breathalyzer test before using the firmware.

**Comment by IncursioHack** [comment]
Dear all, we understand the affection that everyone has for the Bruce firmware, but we are analyzing each feature that will be added, modified or removed from the firmware. At this point this feature will not be implemented.
