### ISSUE TITLE
CYD2USB GPS SUPPORT

### ISSUE THREAD

**Issue by flaryx32** [BruceDevices/firmware#352]
**Describe the bug:**

CYD2USB, cannot detect GPS module.

**Steps To Reproduce:**

- Device used: CYD2USB

**Expected behavior:**

GPS being detected

**Actual behavior:**

GPS not being detected

**Additional context / logs:**

The gps module is connected to the JST 4-pin connector near the MicroUSB port like so:
| GPS | -> | CYD |
|-----|:--:|-----|
| VCC | -> | VIN |
| GND | -> | GND |
| TX  | -> | TX  |
| RX  | -> | RX  |

GPS module used:NEO-6M

Usefull links:
https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display
(They support the GPS with that firmware trough that port so i thought the same but can't find more info for where i should put the module for bruce).

**Comment by IncursioHack** [comment]
Hello flaryx, I don't have the CYD and the GPS you mentioned, in Bruce's code we use the TinyGPS++ library, you must first check if the GPS mentioned is supported by the library in question, if not, we suggest using a GPS supported by the library. 

https://github.com/pr3y/Bruce/blob/3b0166e5f67b3cba2d0bdcb13ee0dedec7287318/src/modules/wifi/wardriving.h#L13

Another case is that the connection needs to follow the platform.io order.

https://github.com/pr3y/Bruce/blob/3b0166e5f67b3cba2d0bdcb13ee0dedec7287318/platformio.ini#L1504

Out of curiosity, also try inverting keeping TX -> RX and RX -> TX.

**Comment by flaryx32** [comment]
Hi IncursioHack, it seems that TinyGPS++ supports my GPS module, 
> Another case is that the connection needs to follow the platform.io order.

can you explain this a bit better i am not sure i understood.

Also at the moment i already soldiererd TX->TX and RX->RX, and since i am learning to soldier i am not really confident in de-soldiering them to re soldier them... So i am sorry abt that :(

**Comment by bmorcelli** [comment]
What's up, man... I made a change in the code to use the pins Marauder use for GPS on Bruce, can you test, please?

It is the beta version

**Comment by flaryx32** [comment]
**bmorcelli** hello :) , thanks for looking into this, installed the beta (5a9c22b) on my CYD2USB with the GPS attached and running the wardriving feature, the light on the GPS blinks and on the screen it says "Waiting for GPS: 400+ seconds" which i assume means that the GPS is still not recognized :(.

Also as i previouseley stated i feel like this might help (i hope so) because it is recognized on this firmware!! :3
> https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display

_Also i know this might be out of topic but if you will, might you look into adding the config for the FM radio feature?_
_I would open another issue/suggestion but i see it says coming soon on the wiki although from my understanding no one is working on this atm!_

**Comment by bmorcelli** [comment]
It is failing to open the HardwareSerial, I don't know why.. I'm waiting for my JST cables to arrive, so I'll be able to test these things without soldering on the board.. 

Nobody is looking into FM radio now afaik, what config you mean? Pin connections?

**Comment by flaryx32** [comment]
_**Woah**_, thanks for the fast response! 
>I'm waiting for my JST cables to arrive

Guess i'll have to wait some more! 


_FM:_
_Referencing this:_
>https://github.com/pr3y/Bruce/wiki/FM#bookmark_tabs-config

_I assume you would be able to config Radio RDM data such as the Radio name or Small text like "You've been bruced" or son titles or something!_
_Also maybe power like from 88 to 115 udb?_
_Maybe more config stuff i am not aware of?_

**Comment by IncursioHack** [comment]
@flaryx32 If you have a case with reference to another module or part of the system, I ask you to open a new issue, otherwise we will lose track of what we can handle and can classify correctly.

If you could add some information about the transmission of an RDM or some functional code, it would help our research :)

**Comment by flaryx32** [comment]
Hi Incursio,
> If you have a case with reference to another module or part of the system, I ask you to open a new issue, otherwise we will lose track of what we can handle and can classify correctly.

Is this in reference to the gps module or to the radio one? thx!

**Comment by flaryx32** [comment]
Hello, any updates on this?

**Comment by IncursioHack** [comment]
> Hello, any updates on this?

We do not have your GPS model for testing. :/  
We have no prediction of when this will be changed.

**Comment by shnmorimoto** [comment]
My module (NEO-6M) is working with the latest beta.

**Comment by flaryx32** [comment]
As of latest beta (aaa3233), gps module seems to be recognized, haven't tested if it gets any satelites because at the moment i am indoors but it is indeed recognized!
