### ISSUE TITLE
Reading arduino serial output on m5stickC plus 2?

### ISSUE THREAD

**Issue by bisaw37** [BruceDevices/firmware#357]
I don't know if this is already possible or not, but I think it would be very useful to me and many others if you could read serial output from an arduino through USB the same way it is read in the "serial monitor" in arduino IDE. Just a little bit ago I was trying to get a diy tachometer to work for my go kart, and I think it would be great to be able to get my pocket sized device and easily diagnose any bugs in my code. Out of all my feature requests on here, this one is by far the one I think would help the most to anyone, not just me.

**Comment by eadmaster** [comment]
Most arduinos have a logic level of 5v that won't play nice with esp32 3.3v gpio pins.

You  need to use a level shifter or an additional module.

For boards with native 3.3v pins you may try this `serial2 read` command and see if it works:
https://github.com/pr3y/Bruce/blob/main/src/core/serialcmds.cpp#L647

Reading directly from usb is also possible on boards with USB host support, but i've never tried that:
https://github.com/tobozo/ESP32-USB-Soft-Host
https://github.com/tobozo/ESP32-USB-Soft-Host/issues/22

**Comment by bisaw37** [comment]
Is there a module that can be connected to give USB host capabilities to a board without it? I have the arduino uno, which does not have USB host.

**Comment by eadmaster** [comment]
It's the other way around: you may need a module to add usb host on the esp32 board running Bruce, like this one:
https://shop.m5stack.com/products/usb-module

Since this requires SPI bus usage, i'd rather give it a try with esp32s3 boards like the Cardputer that would only require the groove port for connection:
https://github.com/hathach/tinyusb

**Comment by bisaw37** [comment]
Could a c9329 module like this work or do I just not really get what you are saying?
https://a.aliexpress.com/_mOHWTfe

**Comment by eadmaster** [comment]
No, ch9329 is useful to add USB HID support, which is a different thing to USB host:
https://github.com/pr3y/Bruce/wiki/Others#using-bad-usb-on-stickcs-and-corecore2-devices

**Comment by bisaw37** [comment]
Ok then, I feel like I got it, thanks.
So basically, the verdict is, it's not possible (or just not practically feasible) to be able to see serial output on the plus2?
Edit: on USB. I forgot to specify that.

**Comment by eadmaster** [comment]
Direct uart pins connection with a level shifter should be the easier way in this case:
https://github.com/pr3y/Bruce/issues/357#issuecomment-2437087057

**Comment by bisaw37** [comment]
Ok then, I'll look into a uart connection. Thanks!

**Comment by eadmaster** [comment]
you may also try with a voltage divider to get the same effect

https://www.reddit.com/r/arduino/comments/sr9qlx/i_tried_to_make_a_voltage_divider_for_connecting/
https://www.reddit.com/r/arduino/comments/1ec9h2c/level_shifting_for_serial_communication/
