### ISSUE TITLE
CYD2USB CC1101 support

### ISSUE THREAD

**Issue by Grzybekrk** [BruceDevices/firmware#358]
**Describe the bug:**
<i have a special slot for cards like for cardputer and instead of g1 and g2 i used pins 21 and 22 

All looks conected correctly good voltage on module but its not working any idea why ![20241025_092914.jpg](https://github.com/user-attachments/assets/83e06f34-23b9-4ed0-9383-5eaa61a879f1)

I tried both slots this one below also and still not working 

In settings i see. Tx and rx so maybe I need use them ? 

Pls help

**Comment by bmorcelli** [comment]
CC1101 pins are hardcoded, and will work only after this last update (1.6.2)... The connector must go to the one beside the SDCard (gpio 22 and 27)

Then you must set the CC1101 in: RF>Config>Module>CC1101 on SPI, if it gives you an error, try switching the pins that come grom 22 and 27 

Explanation: RfTx pin and RfRx pin are used only for other modules that work with a single pin as FS1000A, if ots shown on the RF submenu, cc1101 isn't set

**Comment by Grzybekrk** [comment]
@bmorcelli you are a king ;) it works now I will test it any issues I will let you know

10Q much appreciate

**Comment by bmorcelli** [comment]
Thats great!! So I will close this issue!!

**Comment by AwayGloom** [comment]
Mine sometimes connects to the module and sometimes doesn't, but when I click on scan the esp32 freezes

**Comment by Yag00000** [comment]
gpio 22 and 27 are in distint  JST conectors !!
