### ISSUE TITLE
Brucegotchi deauth not working

### ISSUE THREAD

**Issue by Jethro-San** [BruceDevices/firmware#365]
When I opened up my packet monitor, I noticed that the brucegotchi deauth doesnt even send any deauth packets, let alone deauth the AP, could you please fix this?

**Comment by IncursioHack** [comment]
Could you please add the device you are using, which version of Bruce and the Serial LOGs?

**Comment by Sonys9** [comment]
its works for me, but its very bad catching handshakes :(

**Comment by Jethro-San** [comment]
I am using the cardputer, there was nothing wrong with the install, and I am on 1.6.2
