### ISSUE TITLE
Stick plus2 can't see NRF24

### ISSUE THREAD

**Issue by dis667** [BruceDevices/firmware#366]
When I connect nrf24 to stickc it doesn't see it, but if I choose rf in main menu, then config, and then choose cc1101 it says that it found cc1101.

I've tried change cables and bought new nrf24

**Comment by bmorcelli** [comment]
bad connections, probably your groove connections are not well connected or the connections are mirrored

https://youtu.be/RVQrfghGVqw?si=gKUr12fv1HeGogQ9
