### ISSUE TITLE
[RF] Spectrum not working or slow

### ISSUE THREAD

**Issue by nightflasher** [BruceDevices/firmware#369]
**Describe the bug:**
When using the spectrum function, the display stays mostly on the "start screen" saying 'RF - Scanner' and nothing happens

**Steps To Reproduce:**
- connect the 433MHz module (CC1101) to the M5StickCplus2
- goto RF menu -> config - select module -> CC1101
- enter RF menu again -> spectrum
- wait...

**Expected behavior:**
When i connect my NRF24L01+ and goto NRF24 menu -> Spectrum the spectrum will be shown and bars hoppin around

**Actual behavior:**
1) nothing happpens
2) sometimes some 'like audio signal' waveform shows up and sometimes just a few spikes

**Additional context / logs:**
is this feature not working for me or is my module defective?

**Comment by IncursioHack** [comment]
> * connect the 433MHz module (CC1101) to the M5StickCplus2

Cases where we saw something similar happen, it was either a lack of configuration in RF Frequency, entering the frequency of the device you want to test, or it was the wrong connection or loose wiring.

> * When i connect my NRF24L01+ and goto NRF24 menu -> Spectrum the spectrum will be shown and bars hoppin around

I don't understand this case, are you citing 2 different problems? (CC1101 and NRF24L01)

**Comment by nightflasher** [comment]
No, it's the description of expected behavior - I expect the RF spectrum to act like it does on nrf24l01 spectrum.

**Comment by bmorcelli** [comment]
Nrf24 spectrum is reading Wifi and Bluetooth 2.4Ghz bandwidth, and there are lots of this frequency around us to "poke" the spectrum.. 

Different from 433Mhz, that is waiting for a signal to react.. so it will react and show something on screen if you send a frequency it can read... 

You will have the same behavior if you go the woods (canyons, farms etc), far from Wifi/ble networks..
