### ISSUE TITLE
Add buttons to select or move functions on cyd 

### ISSUE THREAD

**Issue by Trhug25** [BruceDevices/firmware#370]
I find that the touch on the cyd screen is a bit inconvenient and difficult so I am wondering and want to add buttons for the options of moving functions, selecting functions, going back.Replace the touch screen buttons on the cyd. I found that the RGB lights on the cyd are not working and I want to use those light pins as button pins. But I don't know how to modify the source code. There is one more problem. I see cyd has quite few connector pins, can I use pca9548a module or other connector pin expansion modules to expand the connector pins? And does that require modifying the source code? Can you help me please. Thanks. 
![Screenshot_20241030_221802_Shopee](https://github.com/user-attachments/assets/01998bf5-1860-492b-8ff2-386158b19566)
  
![image](https://github.com/user-attachments/assets/1a2fe7c7-3dee-4527-947d-d9edea271611)

**Comment by IncursioHack** [comment]
Hi :) , keep in mind that any modification of the "connection path" will require changes to the code, imagine that it is programmed to perform a function following a specific route, when you add an adapter or hub that changes this route any system would be lost and need This path must be indicated in the code. To do this, I understand that you will need to create this code and test it.


With reference to buttons, CYD's proposal is to use the touchscreen, I see some people using a pen for this. When they opt for the buttons they end up purchasing the Cardputer or the StickC. If you need to insert the buttons into some pins, you will probably need to change the code and say where each pin is and what it will do when you press it. The Platform.io part has some button indications, but again you need to make these changes, soldering and testing.
