### ISSUE TITLE
NRF24 Spectrum "stop" works after using 2.4 Jammer

### ISSUE THREAD

**Issue by wtfkaiba** [BruceDevices/firmware#371]
https://github.com/user-attachments/assets/09cb3698-86b0-42e5-9d8e-2668e6db6a01

Spectrum works fine but when you go for jamming and go back to the spectrum he didn't show any frequencies.
To make the spectrum get back to work I remove and reconnect the 3.3v VCC (red cable in video) and he backs.

- This happens only if you used the 2.4 jammer before enter the spectrum.

- If you only enters in spectrum mode, exit and go back to spectrum it works without issues.

Let me know if more details needed.
**All the best!**

**Comment by bmorcelli** [comment]
Good you opened this issue...  Im aware of this issue, but writing it in here makes us remind of it for future fixes.

Thank you very much

**Comment by smoochiee** [comment]
> Good you opened this issue... Im aware of this issue, but writing it in here makes us remind of it for future fixes.
> 
> Thank you very much

i have pr that fix it...ive change only the stoping method..

**Comment by IncursioHack** [comment]
Solved! Thanks @smoochiee !
