### ISSUE TITLE
CYD support

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#376]
Add ESP32-CYD-3248S035C support(CYD with Capactive touch)

**Comment by IncursioHack** [comment]
https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/issues/41

**Comment by IncursioHack** [comment]
| Board name             |  Pixels                             |  Screen size                | Touch type           |
| ---------------------------| ---------------------------------| ------------------------------| ------------------------|  
| ESP32-2432S024    | 2432 = 240x320 pixels    |  024 = 2.4 inch LCD   | N/A                       | 
| ESP32-2432S028R |  2432 = 240x320 pixels   |  028 = 2.8 inch LCD   |   R = Resistive      | 
| ESP32-3248S035C | 3248 = 320x480 pixels    |  035 = 3.5 inch LCD   |  C = Capacitive     | 


We have 2 problems here, first is to actually check the name of the board and we recommend that when purchasing, please get a product that already has Bruce support, new implementations take time.

The second case is that we do not have the model you mentioned, so it is not possible to test the implementation.

Please provide us with more information regarding the board, its description, pinout and the like.

**Comment by Teapot174** [comment]
ESP32-3248S035C | 3248 = 320x480 pixels | 035 = 3.5 inch LCD | C = Capacitive
https://sl.aliexpress.ru/p?key=CBSzrd8 (Capactive touch)

**Comment by TheMiner203** [comment]
Here is some info, link from Aliexpress page: http://pan.jczn1688.com/directlink/1/ESP32%20module/2.4inch_ESP32-2432S024.zip
