### ISSUE TITLE
Can't connect to wifi after manually adding it to the conf file

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#389]
I was wondering how to add my wifi network creds to the m5stickcplus2 using the .conf file as usual and I noticed that the format has changed quite a bit. So I connected to hotspot using the inbuild keyboard (It connected successfully) and after that I changed the values in the config files for my wifi creds. After that I tried to connect to the router by it was giving that "WiFi offline error".

**Comment by bmorcelli** [comment]
probably you "broke" the json format..

you can edit your file and test its integrity with some online tools like https://jsonlint.com/
