### ISSUE TITLE
Gps not working 

### ISSUE THREAD

**Issue by Trhug25** [BruceDevices/firmware#394]
I have a 6m neo gps module. I have connected the pins as follows 
Vcc - vin
Rx - rx
Tx - tx
Gnd - gnd 
I connected such pins to cheap gold screen cyd 2 usb . But it seems gps does not work, gps waiting time up to 700s but nothing happens.

**Comment by rennancockles** [comment]
Try switching Rx and Tx pins

**Comment by Trhug25** [comment]
> Hãy thử thay đổi chân Rx và Tx

I tried. It still doesn't work.

**Comment by bmorcelli** [comment]
Gps doesn't work on CYD yet

**Comment by Trhug25** [comment]
> Gps vẫn chưa hoạt động trên CYD

Oh. Come to me to run it up to 12000s

**Comment by Trhug25** [comment]
> Gps vẫn chưa hoạt động trên CYD

https://github.com/justcallmekoko/ESP32Marauder/wiki/gps-modification
I wired this project.

**Comment by Trhug25** [comment]
![20241107_062957](https://github.com/user-attachments/assets/09f2f511-ad69-4a41-a81d-ce6d29133765)
![20241107_062952](https://github.com/user-attachments/assets/72b712cc-8498-4744-b227-5ad143a7cd34)
![20241107_062926](https://github.com/user-attachments/assets/65fa3ee3-8904-4ebd-a67e-9fd08f90296d)
N
![20241107_062857](https://github.com/user-attachments/assets/28c15f1e-2842-49d2-9c80-52d927726cf9)
It works when I use io2 
The connection diagram is as follows 
Gnd - gnd
Io22 - tx
Io27 - rx 
3v3 - vcc
