### ISSUE TITLE
Wi-Fi passwords list

### ISSUE THREAD

**Issue by 1337tr** [BruceDevices/firmware#40]
A list of SSID:password made by the user to be used when trying to connect to a Wi-Fi network.
When a Wi-Fi network is required (like web UI) the user first select the network he wants to connect to then the script try to find the password for this network, if the password is found the script ask the user if he wants to use the saved password or a custom password. When user connects to a network and used a custom password, script ask the user if he wants to save this password.
Also when searching and saving passwords make sure it's always lower case (escape upper and lower).

JSON format ex:
```json
{
    "ssid": "password",
    "home": "secret123456",
    "coffee shop": "99CoffeeShop"   
}
```

**Comment by pr3y** [comment]
Awesome ideia!
This will be added in future versions of Bruce :] thx
