### ISSUE TITLE
I can't transfer any files to the cardputer 

### ISSUE THREAD

**Issue by guthubas** [BruceDevices/firmware#404]
I can't transfer any files from my computer to my card. It's giving an upload failure. How can I solve it? 
![IMG_20241108_215317_831](https://github.com/user-attachments/assets/dd161faa-4bf3-4fed-be87-7ae38812cd09)

**Comment by guthubas** [comment]
Cardputer sorry

**Comment by IncursioHack** [comment]
Give us some details about the file, name, size, extension and the like. Another point is that I don't know if you noticed the storage on your Cardputer without the SD card is only less than 2.9MB, that's less than most MP3s that exist today.

**Comment by guthubas** [comment]
These are infrared TV ACs files

**Comment by guthubas** [comment]
How to format SD card in Bruce
