### ISSUE TITLE
Add OpenHaystack support for M5StickC Plus

### ISSUE THREAD

**Issue by avassdal** [BruceDevices/firmware#41]
Hello

Would it be possible to add the key files to the spiffs, and thus not require SD card for Openhaystack?

**Comment by bmorcelli** [comment]
Hello.. yes it is, and actually is a good point..

We'll manage to read the key from LittleFS as well in the next update

**Comment by bmorcelli** [comment]
Done and wait publishing..

If theres no SD, it'll look into LittleFS for the key file
