### ISSUE TITLE
T-Embed-CC1101 bugs

### ISSUE THREAD

**Issue by YANGKUN87** [BruceDevices/firmware#422]
My T-Embed-CC1101 was flashed with bruce, but there were many problems. Some functions could not be exited and I needed to turn off the device and restart it. I hope there is a matching program. Refer to the [hackcube](https://github.com/UnicornTeam/hackcube) project and make it controllable by web ui. It will be easy to use.

**Comment by bmorcelli** [comment]
> Some functions could not be exited

try pressing the upper btn, the one you think is power btn is a GPIO and is being used as ESC btn.
