### ISSUE TITLE
Support for oled display.

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#425]
I'm planning on using the esp32-s3 devkit with the pn532, cc1101 and the nrf24l01. TFT displays use a lot of pins and since bruce fw is using a single color (Except when displaying images) I thought of using an i2c 1.5" oled display 

https://www.aliexpress.com/item/1005006673726980.html?spm=a2g0o.productlist.main.1.7bd3czYVczYVMd&algo_pvid=f9450791-e36f-4f1f-be8b-ded38685af4e&algo_exp_id=f9450791-e36f-4f1f-be8b-ded38685af4e-3&pdp_npi=4%40dis%21LKR%211735.18%211517.98%21%21%2142.74%2137.39%21%40210101f517316683247136050ecc78%2112000037982255853%21sea%21LK%212397466382%21X&curPageLogUid=cXxrP4jxv0uv&utparam-url=scene%3Asearch%7Cquery_from%3A

Will bruce firmware support single color oled displays.

**Comment by bmorcelli** [comment]
I2C displays are not supported by TFT_eSPI library, so it is not (and probably will not be) supported in bruce

**Comment by Z-SHOCK-E** [comment]
Ok. Thanks for the clarification.
