### ISSUE TITLE
Missing Interface.h in repository

### ISSUE THREAD

**Issue by JorgMuskens** [BruceDevices/firmware#429]
**Describe the bug:**
Interface.h is missing from the code in the repository

**Steps To Reproduce:**
NA

**Expected behavior:**
Please upload the missing file. 

**Actual behavior:**
I can not build the latest code anymore due to the missing file. 

**Additional context / logs:**
 Also i need to make a lot of changes to get the code fixed again for running on LilyGO. Looks like a lot of issues with keyboard not sure if the all the code for this is properly excluded wit DHAS_KEYBOARD

**Comment by bmorcelli** [comment]
interface.h files are placed in /ports/DeviceNames/

they are added by the platformio.ini line:
https://github.com/pr3y/Bruce/blob/511baf04fb502309d0e21301b86c6e354ee4fdbc/platformio.ini#L30-L31

and the file is included by device here:
https://github.com/pr3y/Bruce/blob/511baf04fb502309d0e21301b86c6e354ee4fdbc/ports/lilygo-t-deck/platformio.ini#L16
and here
https://github.com/pr3y/Bruce/blob/511baf04fb502309d0e21301b86c6e354ee4fdbc/ports/lilygo-t-deck/platformio.ini#L19

if there were something missing, these Actions wouldn't be successfully completed:
https://github.com/pr3y/Bruce/actions/runs/11865891858

so the project doesn't have these problems you are pointing
