### ISSUE TITLE
Can´t find Pinouts for IR and GPIO for NRF

### ISSUE THREAD

**Issue by HIGHVOLTAGEBEE** [BruceDevices/firmware#435]
Can someone give me the GPIOs pins for IR, NRF24, RF and RFID would be great!
I only could find pictures without the pin numbers but i need the GPIOs 
becaus i want to solder the pins directly to CYD to the ESP32 module?

**Comment by bmorcelli** [comment]
Nrf24 and RF: https://github.com/pr3y/Bruce/wiki/CC1101

IR sensor and LED are GPIO in/out you can connect to the gpio in beside the SdCard and you will set the pins in IR>Config>Ir Tx pin and Ir Rx pin (Rx for receiver and Tx for transmitter)


All the info you need are in the wiki
