### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by dghlkxyvdyxj** [BruceDevices/firmware#436]
1. Add the Possibillity to rename the device the filmware is on
(if possible also make possible to change device type from keyboard to speaker or other device types)

2. Cloning Bluetooth Devices (just like clone portal from the wifi but for bluetooth)

**Comment by QWEIVAN** [comment]
Fix fm module(not found)

**Comment by QWEIVAN** [comment]
please fix the search for fm module on m5stack stick / cardputer because this is a very useful function, or make detailed connection instructions
