### ISSUE TITLE
Bad BLE Ducky Script on M5Stick C Plus 1.1 doesn't work on Windows 11.

### ISSUE THREAD

**Issue by logm1lo** [BruceDevices/firmware#439]
**Describe the bug:**
When I tried to use the Bad BLE Feature on the M5Stick C Plus 1.1 using the dev release (I built it). Everything in Media CMDS works but when I used the ducky script, it doesn't run on my laptop.

**Steps To Reproduce:**
Build the latest build, use the Bad BLE,connect the m5stick to the laptop via bluetooth, use this ducky script: [The_Matrix_Wake_Up.txt](https://github.com/user-attachments/files/17801041/The_Matrix_Wake_Up.txt)

- Device used: M5Stick C Plus 1.1, Windows 11

**Expected behavior:**
The laptop executes the script

**Actual behavior:**
The laptop doesn't executes the script

**Comment by bmorcelli** [comment]
Make sure your stickCPlus2 is not connected to 2 devices at the same time  (smartphone and computer)

**Comment by logm1lo** [comment]
> Make sure your stickCPlus2 is not connected to 2 devices at the same time (smartphone and computer)

I am sure I didn't connect to the smartphone

**Comment by logm1lo** [comment]
Even though I've isolated my smartphone by putting it in the faraday bag, the Bad BLE still doesn't run Ducky script on my windows 11 computer.

**Comment by hunt3rbb666NotFound** [comment]
For me on the same devices mentioned it works perfectly.

**Comment by logm1lo** [comment]
> For me on the same devices mentioned it works perfectly.

that's weird, did you use the firmware you compiled by yourself, or did you use the prebuilt one?

**Comment by hunt3rbb666NotFound** [comment]
both

**Comment by logm1lo** [comment]
> both

well, for me, it's still doesn't do anything
