### ISSUE TITLE
Screen Always On

### ISSUE THREAD

**Issue by GmrsKissimmee** [BruceDevices/firmware#44]
Hello, is it possible to create a standby screen option for all the FW that you have installed on the CP since it consumes quickly if it is on for a long time?

**Comment by xjimwilson** [comment]
this would be really useful, or a screen dim

**Comment by bmorcelli** [comment]
For all the FW, no, because it must be written in every different firmware.. but can be done on bruce, yes.. at least dimming the screen

**Comment by GmrsKissimmee** [comment]
Ok. For your FW it would also be good

**Comment by pr3y** [comment]
Added Dim Time in 1.2.0 version to turn off screen after a while
https://github.com/pr3y/Bruce/commit/12ac90103e1fd360357a32e0054770a7fb911720

**Comment by GmrsKissimmee** [comment]
Excellent, working 100% !!!
