### ISSUE TITLE
Watchy / Yatchy support

### ISSUE THREAD

**Issue by Szybet** [BruceDevices/firmware#440]
Hello
I just want to ask if it would be possible to port https://watchy.sqfmi.com/ and https://github.com/Szybet/Yatchy (Together, they are very similar, just esp32 vs esp32c6)

It would go down to these points:
- Only 4 buttons
- eink screen, so images would be possible but painful to do and colors are not possible, if bruce relies somewhere on them it will suck
- As it's a watch, having only bruce firmware on it would be counter intuitive, so launching it from another firmware, like https://github.com/Szybet/InkWatchy would be the preffered way to do it. The issue is flash size, is it possible to disable (in macro conditions, \#if) certain features like IR, RFID so they don't take up space?
- small display, it's only 200x200

If the answer is "managable" in all points, I might do it one day, for now im just curious.
Thanks

**Comment by bmorcelli** [comment]
couldn´t find documentation about display connection.. if it uses SPI, and is compatible with TFT_eSPI library, it probably can be ported, otherwise it will be a hard task..

**Comment by Szybet** [comment]
Hard task, the matter is if it's possible at all. Ignore that there is no driver support for this screen, what about other things i asked about?
