### ISSUE TITLE
RF Bruteforcer

### ISSUE THREAD

**Issue by Retr0-0Sec** [BruceDevices/firmware#442]
I was thinking could we add something like a RF bruteforcer function? Something like the Sub-GHz bruteforce function in flipper zero🤔

**Comment by bmorcelli** [comment]
First we need to find out how the protocols work, 

we are now capable to bruteforce some of them, line NICE, FAAC amd CAME 12bit, and it will probably come in next weeks or so (not in this next release)

**Comment by borysponchy** [comment]
how to brute force came or nice?

**Comment by bmorcelli** [comment]
Not available yet with bruce, but you can possibly make a .js script to run the commands through interpreter (Scripts)

Can't help with it ryt now, but sending custom commands via serial commands is possible using JavaScript intepreter, and both are documented in the wiki

**Comment by eadmaster** [comment]
You can customize this according to your needs: https://github.com/pr3y/Bruce/blob/main/sd_files/interpreter/rf_brute.js

**Comment by Retr0-0Sec** [comment]
> You can customize this according to your needs: https://github.com/pr3y/Bruce/blob/main/sd_files/interpreter/rf_brute.js

Thanks 🙏
