### ISSUE TITLE
 run on cyd 2,4 ???

### ISSUE THREAD

**Issue by ciccirix** [BruceDevices/firmware#443]
is possible extend  this firmware on ESP32-2432S024 ???

**Comment by bmorcelli** [comment]
It has been already ported, available on BETA (until next release)

Capacitive and resistive screens are supported, you can install in the webflasher on https://bruce.computer/flasher.html

Capacitive was not implemented in the flasher (fyi)

**Comment by ciccirix** [comment]
Thanks bro, What  Device Need select?

Il giorno mar 19 nov 2024 alle 15:01 Pirata ***@***.***> ha
scritto:

**Comment by ciccirix** [comment]
Il giorno mar 19 nov 2024 alle 15:07 Massimo Cingolo ***@***.***>
ha scritto:

**Comment by bmorcelli** [comment]
I don't know the board you have, try both of them

**Comment by ciccirix** [comment]
Li ho provati tutti sto uscendo pazzo


Il giorno mar 19 nov 2024 alle 15:26 Pirata ***@***.***> ha
scritto:

**Comment by ciccirix** [comment]
ESP32-2432S024 è basata sul controller ESP32-D0WDQ6

Il giorno mar 19 nov 2024 alle ore 15:35 Massimo Cingolo ***@***.***>
ha scritto:
