### ISSUE TITLE
Sleep mode not work

### ISSUE THREAD

**Issue by wesamdev** [BruceDevices/firmware#446]
**Describe the bug:**

sleep mode not work the screen not turinng off
**Steps To Reproduce:**

go to config <-- sleep
- Device used: 
m5stickc plus 2
**Actual behavior:**

screen stuck and not turn off untill button pressed

**Comment by lexilexiko** [comment]
Card computer  Same problem. When the device is on, the screen does not go out, which leads to a quick discharge of the screen.

**Comment by bmorcelli** [comment]
Please test BetaRelease..

Install BetaRelease at https://bruce.computer/flasher.html

**Comment by wesamdev** [comment]
> Please test BetaRelease..
> 
> Install BetaRelease at https://bruce.computer/flasher.html

thanks problem has been fixed!
