### ISSUE TITLE
Latest release doesn't boot M5StickC Plus2

### ISSUE THREAD

**Issue by goliath29** [BruceDevices/firmware#448]
**Describe the bug:**
The latest release refuses to boot. The green status light turns on, only when the button is pressed.
I have tried with M5 Launcher and with a direct flash, neither boots.

**Steps To Reproduce:**
Re-flashed the device, still refuses.
- Device used: 

**Expected behavior:**
Boot to the Bruce screen.

**Actual behavior:**
Status light only stays on when the power button is held down, turns off when the button is released.

**Additional context / logs:**
The device boots when flashed with the previous release, both through M5 Launcher and a direct flash.

**Comment by bmorcelli** [comment]
You dont need to keep pwr btn held until screen comes up, otherwise it will shutdown immediately.

Hold pwr btn for 4 seconds, release and wait a little more, it will work.. have patience..

I got it enhanced in the beta version, but wont be THAT fast too..
