### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by vexyywdw** [BruceDevices/firmware#45]
add some templates for badusb and add ble support also make a folder here that has every bin of bruce 
example:
brucecardputer.bin ect.
that will make it easier to use with m5launcher

**Comment by Lamnxzp** [comment]
build it yourself

**Comment by bmorcelli** [comment]
The binaries of bruce are shared in [This link](https://github.com/pr3y/Bruce/releases)

This is the Releases page...

BLE keyboard is in our radar.. sometime in the future we will make it happen, but badUsb scripts there are many [in Here](https://github.com/SeenKid/flipper-zero-bad-usb)
