### ISSUE TITLE
M5StickCPlus2 Flash Tool Error 

### ISSUE THREAD

**Issue by ATOMNFT** [BruceDevices/firmware#458]
**Upon connecting and then trying to install I'm presented with a error that states "Failed to download manifest"**

**Steps To Reproduce:**

- Device used: M5StickCPlus2 
- Try to use web flasher to flash latest bruce to M5StickCPlus2

**Expected behavior:**
Flash tool to start the flashing process and me to wait. 

**Actual behavior:**
"Failed to download manifest" error after choosing the port and hitting connect.

**Comment by bmorcelli** [comment]
Hey buddy, we just changed our main workflow, and it need a new release to work ;)

We are releasing 1.7.2 in a few minutes.. beta version flasher is supposed to be working

**Comment by bmorcelli** [comment]
Working now! Thank you!! 🙏🙏

**Comment by ATOMNFT** [comment]
> Working now! Thank you!! 🙏🙏

Thank you for your dedication and work on Bruce!!!!
