### ISSUE TITLE
RF spectrum not working

### ISSUE THREAD

**Issue by xjimwilson** [BruceDevices/firmware#46]
Unless I have not set up my receiver correctly, the rf function crashes often, and when it does work it freezes after 2 seconds.

**Comment by fgsilva12** [comment]
does not work here. Freezes and restarts.

**Comment by vladirocox** [comment]
same

**Comment by SilvioCruzDeveloper** [comment]
To com mesmo Problema

**Comment by bmorcelli** [comment]
Found the bug...

In the last update of arduino framework for esp32 the parameters of the function rmt_config() have changed, and the Macro ESP_ERROR_CHECK() is making it reboot after the error message on Serial...

You'll find the call for this function on line 39 of src/rf.cpp file

Now we can search for a way to fix it..

**Comment by bmorcelli** [comment]
Wull be fixed in https://github.com/pr3y/Bruce/pull/71
