### ISSUE TITLE
Bruce for cyd esp32-2432S024C ( capacitive touch )

### ISSUE THREAD

**Issue by 189653423** [BruceDevices/firmware#461]
Hi, please make a firmware for cyd esp32-2432S024C 2.4”.

**Comment by Asmodeux2** [comment]
CYD-2432W328C_2 install this firmware on WebFlasher

https://bruce.computer/flasher

**Comment by Asmodeux2** [comment]
And close issue

**Comment by bmorcelli** [comment]
hecho
feito
done
fatto
fait

available on webflasher
