### ISSUE TITLE
CYD support (2.4+Capactive)

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#462]
https://esp.huhn.me/

0х1000 - Bootloader
0х8000 - Partition
0x10000 - Firmware
![image](https://github.com/user-attachments/assets/460d055f-d896-42e7-aea3-44ca5ac9060b)
![image](https://github.com/user-attachments/assets/475d0d36-329f-4c18-94fb-3a0509a2f9ae)

[firmware.zip](https://github.com/user-attachments/files/17843305/firmware.zip)

**Comment by Asmodeux2** [comment]
Уже добавили под другим названием CYD-2432W328C_2

**Comment by Asmodeux2** [comment]
Я ранее уже просил @bmorcelli добавить его как в WebFlasher так и в Release. Просто название от прошивки донора так и осталось с поддержкой CST820. Которую кстати ты просил

**Comment by bmorcelli** [comment]
I need the interface files to add to the project.. 

interface.cpp. interface.h and platformio.ini for this device

Webflasher is driven by an automated workflow, so it won't be possible to only add the binaries there

**Comment by bmorcelli** [comment]
Dnoe

**Comment by ciccirix** [comment]
![1bb0f53c-e81d-422b-bc55-92c1c81cbc29](https://github.com/user-attachments/assets/ad583bac-659d-4ce2-897f-5f3b5e528ce4)
  not work on me..

**Comment by ciccirix** [comment]
si ferma su quella schermata

**Comment by Asmodeux2** [comment]
> ![1bb0f53c-e81d-422b-bc55-92c1c81cbc29](https://github.com/user-attachments/assets/ad583bac-659d-4ce2-897f-5f3b5e528ce4)
>   not work on me..

https://telegra.ph/Kak-opredelit-CYD-11-21

You use ESP32-2432S024(R) firmware work on ESP32-2432S024(C)

**Comment by Asmodeux2** [comment]
> ![1bb0f53c-e81d-422b-bc55-92c1c81cbc29](https://github.com/user-attachments/assets/ad583bac-659d-4ce2-897f-5f3b5e528ce4)
>   not work on me..

Use CYD-2432S028 firmware on your ESP32-2432S024R

![Screenshot_20241121_170242_Chrome.jpg](https://github.com/user-attachments/assets/c7388376-4a8c-4ced-9b30-eb62891726db)
