### ISSUE TITLE
UK keyboard

### ISSUE THREAD

**Issue by brettputer** [BruceDevices/firmware#47]
Anyone managed to find a UK Keyboard layout,  \ translates to # seems to be the main issue when using EN_US

**Comment by bmorcelli** [comment]
Ok, I'll look into it..

**Comment by mtclpt** [comment]
I can suggest this project to help develop the functionalities of:
-Wireless BadUSB over a WiFi AP
-BadUSB on M5StickC (..WiFi Duck and utilizes the native USB function of ESP32 S2/3 chip. As a result, you can run WiFi Duck with a default module below 10$..)
-Add Keyboard layouts

https://github.com/wasdwasd0105/SuperWiFiDuck

**Comment by bmorcelli** [comment]
[Bruce3_Cardputer.zip](https://github.com/user-attachments/files/16401613/Bruce3_Cardputer.zip)
@brettputer Can you please validate the Bad Usb with the "en-UK" keyboard, please?

**Comment by bmorcelli** [comment]
implemented[ here ](https://github.com/pr3y/Bruce/pull/95)
