### ISSUE TITLE
nrf24 is not being detected on the cyd

### ISSUE THREAD

**Issue by zelamus** [BruceDevices/firmware#471]
Website shows that cyd supports nrf24 but in the information option of the nrf24 it says that module is not detected,my board is an ESP32-2432S028 with microusb

**Comment by bmorcelli** [comment]
bad connections, probably.. i have it running here with the schematics shown in the wiki

**Comment by gghhnnkk657** [comment]
does anyone have a connection diagram?

**Comment by ptegler** [comment]
[https://drive.google.com/drive/folders/1Ulre0C8hjttorN-CC2DiCCgddaOiemYv](https://drive.google.com/drive/folders/1Ulre0C8hjttorN-CC2DiCCgddaOiemYv)
and [https://www.youtube.com/watch?v=KwUs8eVlG3U](https://www.youtube.com/watch?v=KwUs8eVlG3U
)

**Comment by qyzwjt49rr-glitch** [comment]
Hi, I have the NRF24 NOT detected on. my CYD. i have then flashed the CYD HAT bin and it gives me the same error message, telling me to flash the NO HAT bin, which i have done in the first place and gave me the error message the first time...
