### ISSUE TITLE
Workflow: deauth flood + raw sniffer (eapol hs)

### ISSUE THREAD

**Issue by hunt3rbb666NotFound** [BruceDevices/firmware#472]
Hi, thank you for this gem. In my opinion, we would need, if we wanted, to be able to keep the flood deauth active in the background so that we could capture the eapols of the hs file that are used for cracking the wifi password. Without keeping the flood deauth active, we have to wait for someone to connect to the wifi we are testing. It's very good that we can already choose the channel and be faster in the attack, but by maintaining the deauth flood you can do it in less than 5 seconds if the distance is right. Thank you again for what you do.

**Comment by LZ2DMV** [comment]
That is what the Brucegotchi app does, no need to do deauth from the raw sniffer. Just use Brucegotchi.

**Comment by hunt3rbb666NotFound** [comment]
thx!
