### ISSUE TITLE
bad usb at cyd

### ISSUE THREAD

**Issue by khanh-lol** [BruceDevices/firmware#475]
hi bruce team, how to use badusb at cyd?

**Comment by Ademolght** [comment]
> hi bruce team, how to use badusb at cyd?

imposible

**Comment by BeqaMiqa** [comment]
here is the guide for it, but there isn't cyd mentioned anywhere:
https://github.com/pr3y/Bruce/wiki/Others#badusb

in short you will have to buy a CH9329 module. If you do, update us please.

**Comment by khanh-lol** [comment]
> here is the guide for it, but there isn't cyd mentioned anywhere: https://github.com/pr3y/Bruce/wiki/Others#badusb
> 
> in short you will have to buy a CH9329 module. If you do, update us please.

im have it the CH9329, but what i can do now?

**Comment by BeqaMiqa** [comment]
> > here is the guide for it, but there isn't cyd mentioned anywhere: https://github.com/pr3y/Bruce/wiki/Others#badusb
> > 
> > in short you will have to buy a CH9329 module. If you do, update us please.
> 
> im have it the CH9329, but what i can do now?
 
At the bottom next to the micro USB or type c (depends on which version of the cyd you have) there are 4 pins labeled VIN RX TX GND.

This is the connection:
CYD       CH9329
Rx     ->     tx
Tx     ->     rx

If you need an example script to run here it is:

https://github.com/pr3y/Bruce/blob/main/sd_files%2FBadUSB%20and%20BlueDucky%2FBruce_t_Best.txt

Upload this txt file on the SD card and then select it from the badusb options on the CYD 

In theory this should work (hopefully), let me know if it does

**Comment by khanh-lol** [comment]
ty man

**Comment by BeqaMiqa** [comment]
If you don't mind could you comment few pictures or a short video of it working please

**Comment by khanh-lol** [comment]
> If you don't mind could you comment few pictures or a short video of it working please

my computer dont have a camera, sorry

**Comment by khanh-lol** [comment]
it working

**Comment by khanh-lol** [comment]
burhh someone is stole my CH9329

**Comment by khanh-lol** [comment]
3$ :\

**Comment by BeqaMiqa** [comment]
Also I forgot to say, if ch9329 module outputs 5v on it's TX pin you'll need a level shifter so it won't fry the esp

**Comment by khanh-lol** [comment]
> Also I forgot to say, if ch9329 module outputs 5v on it's TX pin you'll need a level shifter so it won't fry the esp

k
