### ISSUE TITLE
Interpreter CYD

### ISSUE THREAD

**Issue by BeqaMiqa** [BruceDevices/firmware#476]
the interpreter and Scripts functions are not working for CYD
I'm using CYD micro usb version(CYD-2432S028)

As i've understood it should run simple tft commands

when i try to run it by selecting the js file the program it stops with blank screen only showing the navigation and the select buttons and then reboots itself

Am i missing a step because in the main page it says that this feature is supported.

**Comment by bmorcelli** [comment]
indeed it is not working due to hardware limitations.. i will take it from the list
