### ISSUE TITLE
Problem with Costum IR

### ISSUE THREAD

**Issue by AzhariRamadhan** [BruceDevices/firmware#48]
https://github.com/pr3y/Bruce/assets/32870854/b5426bec-c87c-48b1-855e-46098df3c3da

**Comment by bmorcelli** [comment]
Hello,

there are some protocols that are not implemented yet.. i'm working on that.. the challange is on how to transform the command and address from the IRDB file into the data entry of the functions we have available..

I'm working on that.

**Comment by eadmaster** [comment]
See the code i've written in my fork, it may help
https://github.com/pr3y/Bruce/issues/64#issuecomment-2226923039

**Comment by bmorcelli** [comment]
I Guess it was fixed in [version 1.2.1 ](https://github.com/pr3y/Bruce/releases/tag/1.2.1)
