### ISSUE TITLE
Interface optimization

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#491]
Hello, I want to ask you to optimize the interface. There are extra sections that need to be removed to the Others tab: Scripts (it definitely shouldn't be on the main page), Clock (a function that may be useless on some devices, for example CYD, after each shutdown, time data is erased), Connect (a function that is quite useful, but not in demand due to bugs).
And now about the sections that should be added to the main page: Bad KB(must be added to the main page, and must contain BadUSB and BadBLE).

Please do it😀

**Comment by IamNobody96** [comment]
Hi.
I'm not a contributor but I could make that.

**Comment by 9dl** [comment]
I'm working on this :)

**Comment by eadmaster** [comment]
related for the 1st part: https://github.com/pr3y/Bruce/issues/326
