### ISSUE TITLE
BLE Spam and glitches

### ISSUE THREAD

**Issue by Danyokkk** [BruceDevices/firmware#493]
I have problems with version 1.7.2, when I want to spam Android devices, I select them, and then afterwards, when I want to spam, for example, iOS devices, my M5 stick restarts. When I want to change the brightness and I am at 100% brightness and then click the upper button on the M5 stick, the M5 stick restarts.

- please fix this, in general, the BLE spam, especially on IOS systems is very very poor
- spam ios is just once there are AirPods and then you cancel it and then nothing happens android it restarts but yea does nothing almost

https://github.com/user-attachments/assets/c75169f4-8af5-42d7-be62-c439cb8db614

**Comment by bmorcelli** [comment]
fixed on beta
