### ISSUE TITLE
brutegotchi captures hs files without actually checking that the file is complete.

### ISSUE THREAD

**Issue by hunt3rbb666NotFound** [BruceDevices/firmware#496]
Hi brother, brutegotchi sometimes doesn't capture valid hs file. Could a check be added so that before saving the hs files it is checked that they are complete with bssid etc? This happens very often.

![image](https://github.com/user-attachments/assets/60bb6fc2-5c62-4412-805d-bd53dcf723a6)

![image](https://github.com/user-attachments/assets/1f0c2a17-2ccc-4452-87bc-53e76d66c954)

![image](https://github.com/user-attachments/assets/22622d55-eb7d-441e-ba80-347ab983373a)

![image](https://github.com/user-attachments/assets/c7b08f94-978d-4c46-aff3-4ec572326434)

![image](https://github.com/user-attachments/assets/4d806d71-b7cf-4803-81b7-b25ee36fe859)

It would be really nice to do a check before the files are saved. Or am I missing something?

**Comment by bmorcelli** [comment]
packets come and go very fast.. it is very hard to keep validating the files while it is running.. sometimes the capturing misses things due to low power or different channels
