### ISSUE TITLE
Fixing the RF bug

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#499]
Large .sub signals cannot be reproduced. I tried playing signals for brute force, for example .a sub with 1024 signals is played on CatHack firmware, but a couple of seconds pass on Bruce, and sometimes a millisecond and playback ends

**Comment by eadmaster** [comment]
Dup?
https://github.com/pr3y/Bruce/issues/362

**Comment by Teapot174** [comment]
it plays short RAW signals.

**Comment by bmorcelli** [comment]
Some files have more than one signal, like that: https://github.com/Zero-Sploit/FlipperZero-Subghz-DB/blob/main/subghz/Doorbells/AVANTEK/AVANTEK_Mini_CB11_Repeating.sub

Big files compress the signal into one big string
https://github.com/pr3y/Bruce/blob/955dd7b9099e76d471e82d068d16193c157086e1/src/modules/rf/rf.cpp#L1252

It can be enhanced, to send each signal separately, but I didn't think about a good solution for it
