### ISSUE TITLE
Please respond. The red led on m5stickc plus 2 remains on while using the custom ir function.  

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#50]
The red led on M5stickc plus 2 stays on after the ir signal is transmitted. Not only while the the signal is transmitted. Please fix this on the next update. There are some more fixes that will be great if done. I'll post them as separate issues.

**Comment by bmorcelli** [comment]
Wull be fixed in https://github.com/pr3y/Bruce/pull/71
