### ISSUE TITLE
bug freeze RF

### ISSUE THREAD

**Issue by Poussistar** [BruceDevices/firmware#503]
Hello Bruce team,

I have installed version 1.7.2 of Bruce on my M5Stick Plus 2. When I connect my CC1101 module using the GPIO pins as described in the Bruce wiki, it is detected correctly. However, when I try to start Scan/Copy or Jammer Full, the screen freezes until I disconnect the CC1101 module.

I would like to know if the issue is caused by my CC1101 module, the firmware, or my M5Stick itself.

Thank you in advance!

**Comment by bmorcelli** [comment]
It usually is bad connections in the grove port.. 

stick is waiting for MISO pin go to LOW state, and if it cant be detected, it freezes (library behavior)
