### ISSUE TITLE
Brucegotchi impossible to use sub-menu - Lilygo T-Embed CC1101

### ISSUE THREAD

**Issue by rustysun9** [BruceDevices/firmware#504]
**Describe the bug:**

While Brucegotchi is running, it is impossible to use menu which pops up when middle button is pressed. Menu exits within 1 sec.

**Steps To Reproduce:**

- Device used:  Lilygo T-Embed CC1101 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
 
Firmware version installed is latest. Bruce 1.7.2

**Comment by shnmorimoto** [comment]
I think the Beta version fixes it, so could you try it?

**Comment by rustysun9** [comment]
Hi Shnmorimoto,

You are correct. Issue is not observed on beta version.

Thanks for reply
