### ISSUE TITLE
Can i use it with SSD1306

### ISSUE THREAD

**Issue by b1scuitdev** [BruceDevices/firmware#505]
Can i use it with SSD1306 128x64 display, ESP32 WROOM32U

**Comment by bmorcelli** [comment]
Afaik this display is not compatible with TFT_eSPI library, so it can't be easily ported..

And the screen is too small for bruce.. it needs at least 128 pixels of height to work well and show all information it needs to be shown..

**Comment by b1scuitdev** [comment]
![image](https://github.com/user-attachments/assets/8f3567f4-6ce8-4d1d-a0ec-284da58c2445)

Maybe this one? 240x240 1.3" IPS TFT Display (ST7789 Controller)
7 pin connection
GND
VCC
SCL SPI
SDA SPA
RES
DC Data
Backlight

**Comment by bmorcelli** [comment]
Yes, this guy is supported by the library

**Comment by b1scuitdev** [comment]
> Yes, this guy is supported by the library 

Thank you :)
