### ISSUE TITLE
cyd not working after flashing

### ISSUE THREAD

**Issue by idk-br9** [BruceDevices/firmware#506]
i tried to flash bruce after marauder, webflasher stuck on 60% and crashed with "device lost". My cyd is not working now, i tried erasing firmware and flashing marauder back, webflasher said the device has been lost too. All i have is red led in top-left of display module. Help
esp32-2432s024

**Comment by bmorcelli** [comment]
You migh have had a problem with your USB cable..

the flasher gets "stuck"sometimes, but fear not, it is working in the background, just don't unplug the usb.
