### ISSUE TITLE
When will this feature be added? (PN532 Emulation)

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#509]
Why haven't we added the pn532 emulation yet, you've already shown its demonstration and as I understand it, it's already been done

Video from the developer
https://github.com/user-attachments/assets/313906bc-66ce-4e4d-a66d-0154c2370d6f

**Comment by bmorcelli** [comment]
Because PN532 changes the 3rd bit of the emulated tag, invalidating the whole thing..

So the tag you are emulating is different from the one you are trying to emulate, and it won't work at all..

**Comment by jakre1234** [comment]
Can the emulation be done with the m5 rfid module?

> Because PN532 changes the 3rd bit of the emulated tag, invalidating the whole thing..
> 
> So the tag you are emulating is different from the one you are trying to emulate, and it won't work at all..

can the emulation be done with m5stack rfid module?

**Comment by jakre1234** [comment]
Can the emulation be done with the m5 rfid module?

> Because PN532 changes the 3rd bit of the emulated tag, invalidating the whole thing..
> 
> So the tag you are emulating is different from the one you are trying to emulate, and it won't work at all..

can the emulation be done with m5stack rfid module?

**Comment by bmorcelli** [comment]
No, it is not possible

**Comment by jakre1234** [comment]
So I can not simply emulate now or in future but can write the data to any rfid card which supports rewriting block 0 and use that card, right?

**Comment by jakre1234** [comment]
So I can not simply emulate now or in future but can write the data to any rfid card which supports rewriting block 0 and use that card, right?

> No, it is not possible
So I can not simply emulate now or in future but can write the data to any rfid card which supports rewriting block 0 and use that card, right?

So I can not simply emulate now or in future but can write the data to any rfid card which supports rewriting block 0 and use that card, right?

**Comment by bmorcelli** [comment]
It can read and write tags (I can't tell you about block 0, I personally don't know).

Emulation is not available on M5Stack RFID/2 modules, only in PN532 with some restrictions 

AlEdit: And bruce doesn't emulate yet

**Comment by CloudWaddie** [comment]
https://github.com/Seeed-Studio/PN532/issues/88
