### ISSUE TITLE
Applejuice cannot select device.

### ISSUE THREAD

**Issue by Bulkoa** [BruceDevices/firmware#51]
I cant select the device to advertise in bluetooth applejuice.

**Comment by Z-SHOCK-E** [comment]
Same here.

**Comment by ZOZO25** [comment]
bonjour je ne suis pas le créateur du firmware mes d'après moi c'est normale tout les iPhone compatible avec le hack vont être touchez tans qu'il sont dans le rayon Bluetooth soit un peut près 10M, d'après moi on ne peut pas choisir et c'est normale

**Comment by Bulkoa** [comment]
Sorry if i was unclear but i mean the bluetooth data to advertise like ipods appletv not device to advertise to.
