### ISSUE TITLE
RF  Scan/copy function issue

### ISSUE THREAD

**Issue by rustysun9** [BruceDevices/firmware#513]
**Describe the bug:**

I am testing CC1101 RF Scan/copy function using subGHz garage opener remote while monitoring sent data with Airspy mini. 
I noticed that when signal from garage remote is captured (freq 433.89MHz) and after replied, sent data is always on a little bit higher frequency. In my case 433.916MHz.

**Steps To Reproduce:**

Capture data using frequency range or fixed frequency setting in Bruce. Send captured RAW data. Compare Tx freq from garage remote with Tx frequency sent by Bruce firmware installed device. 

- Device used: LILYGO T-Embed CC1101 on Bruce beta firmware aa311b1

**Expected behavior:**

Captured data to be sent on same frequency as it was received and captured by garage opener remote.

**Actual behavior:**

**Additional context / logs:**

On shared image, you can see difference between remote and bruce Tx data. 
Lower marked signal on airspy waterfall is garage opener Tx data and top is captured and replied data from bruce device.
![Screenshot_2024-12-03_21-50-25](https://github.com/user-attachments/assets/5c3f8406-7cd1-4dbb-82bf-6df21295cd88)

**Comment by synl0rd** [comment]
I am a beginner and new to using Bruce with the M5Stick Plus2 device. I have completed the wiring to the CC1101, and there are no errors when selecting CC1101 in the configuration. I tried scanning/copying from my Ford car remote, and it was detected and saved. However, replaying the signal does not work. The same issue occurs with several other remotes on the same frequency. I am not sure if the problem lies in the scan/copy process, making the replay fail, or if there is a bug in the transmission process.

**Comment by bmorcelli** [comment]
> I tried scanning/copying from my Ford car remote, and it was detected and saved. However, replaying the signal does not work

RAW signals are not good enough.. I am working on that..

Car key fobs usually has Rolling code technology.. so they are almost immune to replaying 


> I noticed that when signal from garage remote is captured (freq 433.89MHz) and after replied, sent data is always on a little bit higher frequency. In my case 433.916MHz.

CC1101 isn't that sharp on frequency setting.. and there are some percentage of errors on the chip and antennas..

This difference of frequency would hardly affect receiver...

If you have read RAW data, it is possible that the noise have filled most of the signal, I'm working on that right now, and other thing is that RAW signals are being sent only Once, and sometimes it isn't enough time for the receiver to process and decode... I'm changing it to repeat these raw signals at least 3 times (decoded signals are repeated 10 times)

**Comment by rustysun9** [comment]
Hi Pirata, thank you for your reply and explanation. Importance of matching frequency really depends on receiver. 
Some will react to whatever you throw at them. Freq offset for them can be quite big. 
Others needs multiple repeats on almost exact frequency to wake up.
BTW great project and community.

**Comment by bmorcelli** [comment]
> Some will react to whatever you throw at them. Freq offset for them can be quite big.

Yes.. Im facing it now that I'm working on the RAW capture.. not an easy task... Repeating RAW data 3 times lead to 6 to 9 total signals (usually) I think its enough, but its a guess only..

> BTW great project and community

Thank you!!

**Comment by synl0rd** [comment]
@bmorcelli Thank you for reply. Does the latest commit in the master branch also get updated every time the latest firmware version is flashed at https://bruce.computer/flasher ?

**Comment by bmorcelli** [comment]
Yes.. it is available in the BetaRelease

**Comment by BasilBrush73** [comment]
HI, I too have noticed that the transmitter on my M5Stack Cardputer ADV Hydra-RF 424 Devboard Pro（NRF24 + CC1101 2-in-1）is 20khz higher than the listed frequency. Does Bruce offer a frequency offset to compensate?
