### ISSUE TITLE
RF cc1101 scan/copy spectrum

### ISSUE THREAD

**Issue by hunt3rbb666NotFound** [BruceDevices/firmware#516]
Hi, thank you again for your project. I bought the cc1101 module and connected it to my m5stickc plus 1.1 and noticed that the RF scan/copy function with the beta version works perfectly, so every signal is taken and I can choose what to do. On the other hand, in version 1.7.2 the frequency moves by itself and the raw signal is not captured and if it does, it continues in a loop without stopping. I have configured the rx and tx pins for both versions. Am I doing something wrong or are there any problems with this version for cplus 1.1? The Spectrum also remains locked.
Thank you for your time and for what you do for the community.

**Comment by bmorcelli** [comment]
> Am I doing something wrong or are there any problems with this version for cplus 1.1?

No, the code in beta fixed the issue of version 1.7.2, and this problem was present in almost all devices, only T-Embed CC1101 was working fine due to the way CC1101 is connected to the MCU... A new version will be released soon.

**Comment by hunt3rbb666NotFound** [comment]
Perfect, thank you very much.
