### ISSUE TITLE
Bruce gotchi.

When enabled just makes a hotspot called 
"ESP 565F94". It does not capture any handshakes and the hotspot cannot be connected to. 

1.7.2



### ISSUE THREAD

**Issue by TYTTVN** [BruceDevices/firmware#521]
**Describe the bug:**

**Steps To Reproduce:**

- Device used: cardputer

**Expected behavior:**

**Actual behavior:**

**Comment by bmorcelli** [comment]
handhsakes are captured when devices in the area try to connect into networks, an brucegothi is in this same channel.. so it is something that mus be kept running for long times..

the acuracy is better if it is near the devices that are connecting due to the power of ESP32 antenna.
