### ISSUE TITLE
Esp32-s3 devkit n16r8 compile error when compiling with -DHAS_SCREEN=1

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#527]
I get this error when I compile Bruce for the esp32-s3 devkit (n16r8)

src/core/mykeyboard.cpp: In function 'bool checkEscPress()':
src/core/mykeyboard.cpp:122:29: error: 'BTN_ACT' was not declared in this scope
     if(digitalRead(UP_BTN)==BTN_ACT)
                             ^~~~~~~
src/core/mykeyboard.cpp:122:29: note: suggested alternative: 'HTTP_ACL'
     if(digitalRead(UP_BTN)==BTN_ACT)
                             ^~~~~~~
                             HTTP_ACL
*** [.pio/build/esp32-s3-devkitc-1-psram/src/core/mykeyboard.cpp.o] Error 1

I used these pins for the 1.9 TFT btw

scl 36
sda 35
rst 15
dc 16
cs 39
BLK 17

**Comment by bmorcelli** [comment]
add this line in platfomio.ini... if the btn is pressed all the time, change it to HIGH

-DBTN_ACT=LOW
