### ISSUE TITLE
Bruce ui won't fit inside the 170x320 st7789 1.9" tft display

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#531]
I got bruce working with my 1.9" tft display. I tried swapping the height and width of the display but the ui won't fit perfectly with the display

**Comment by rouing** [comment]
You mean you wanted the orientation to be vertical? This is not going to work.

See this: #537

**Comment by rouing** [comment]
@bmorcelli NP, To Close.

**Comment by pepek23588** [comment]
> I got bruce working with my 1.9" tft display. I tried swapping the height and width of the display but the ui won't fit perfectly with the display

What board did you use esp 32 d?

**Comment by Z-SHOCK-E** [comment]
> > I got bruce working with my 1.9" tft display. I tried swapping the height and width of the display but the ui won't fit perfectly with the display
> 
> What board did you use esp 32 d?

Esp32s3 devkit

**Comment by vancep320-droid** [comment]
i also have this problem, any fix? i found out that marauder had the same problem with the st7789 and its because of a display driver incompatibility, luckily someone made a fix for that.
