### ISSUE TITLE
I need help for buttons

### ISSUE THREAD

**Issue by b1scuitdev** [BruceDevices/firmware#532]
Im trying to control bruce by buttons on my ESP WROOM32U, my project is based on m5stickcplus2 port I changed the platformio board and etc to upload code also I set button pins but they aren't working?

[env:m5stack-cplus2]
platform = https://github.com/bmorcelli/platform-espressif32/releases/download/0.0.4/platform-espressif32.zip
board = esp32dev
framework = arduino
board_build.partitions = custom_4Mb_full.csv
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
;upload_speed = 921600
build_src_filter =${env.build_src_filter} +<../ports/m5stack-cplus2>
build_flags =
	${env.build_flags}
	-Iports/m5stack-cplus2
	-Os
	-DCORE_DEBUG_LEVEL=5

	-DNEW_DEVICE=1 	;key for new device,
	;-DSTICK_C_PLUS2=1

	;Features Enabled
	;-DLITE_VERSION=1 ;limits some features to save space for M5Launcher Compatibility
	-DMIC_SPM1423=1 ;Applicable for SPM1423 device
	;FM Radio
	-DFM_SI4713=1 ;Uncomment to activate FM Radio using Adafruit Si4713
	-DFM_RSTPIN=0
	-DPIN_CLK=0
	-DI2S_SCLK_PIN=0
	-DI2S_DATA_PIN=34
	-DPIN_DATA=34

	;Have RTC Chip
	-DHAS_RTC=1

	;Have buzzer
	-DBUZZ_PIN=2

	;Can run USB as HID
	;-DUSB_as_HID=1 ;uncomment to enable
	;-DBAD_TX=25 ; Using pin header
	;-DBAD_RX=26 ; Using pin header
	-DBAD_TX=32  ; Using Grove
	-DBAD_RX=33	 ; Using Grove

	;Buttons configuration
	-DHAS_BTN=1
	-DSEL_BTN=14
	-DUP_BTN=27
	-DDW_BTN=12
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"M5"'

	;-DALLOW_ALL_GPIO_FOR_IR_RF=1 ; Set this option to make use of all GPIOs, from 1 to 44 to be chosen, except TFT and SD pins

	;Infrared Led default pin and state
	-DIR_TX_PINS='{ {"Default", LED}, {"M5 IR Mod", GROVE_SDA}, {"G26",26}, {"G25",25}, {"G0",0}, {"Groove W", GROVE_SCL}, {"GROVE Y", GROVE_SDA}}'
	-DIR_RX_PINS='{ {"M5 IR Mod", GROVE_SCL}, {"G26",26}, {"G25",25}, {"G0",0}, {"Groove W", GROVE_SCL}, {"GROVE Y", GROVE_SDA}}'
	-DLED=19
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	;Radio Frequency (one pin modules) pin setting
	-DRF_TX_PINS='{ {"M5 RF433T", GROVE_SDA}, {"G26",26}, {"G25",25}, {"G0",0}, {"Groove W", GROVE_SCL}, {"GROVE Y", GROVE_SDA}}'
	-DRF_RX_PINS='{ {"M5 RF433R", GROVE_SCL}, {"G26",26}, {"G25",25}, {"G0",0}, {"Groove W", GROVE_SCL}, {"GROVE Y", GROVE_SDA}}'

	; connection pins for CC1101 https://github.com/bmorcelli/io433/blob/master/platformio.ini
	-DUSE_CC1101_VIA_SPI
	-DCC1101_GDO0_PIN=25
	-DCC1101_SS_PIN=SPI_SS_PIN
	-DCC1101_MOSI_PIN=SPI_MOSI_PIN 
	-DCC1101_SCK_PIN=SPI_SCK_PIN
	-DCC1101_MISO_PIN=SPI_MISO_PIN
	;-DCC1101_GDO2_PIN=-1

	; connections are the same as CC1101
	-DUSE_NRF24_VIA_SPI
	-DNRF24_CE_PIN=25
	-DNRF24_SS_PIN=SPI_SS_PIN
	-DNRF24_MOSI_PIN=SPI_MOSI_PIN
	-DNRF24_SCK_PIN=SPI_SCK_PIN
	-DNRF24_MISO_PIN=SPI_MISO_PIN

	;Battery ADC read pin
	-DBAT_PIN=38

	;Font sizes, depending on device
	-DFP=1
	-DFM=2
	-DFG=3

	;Screen Setup
	-DHAS_SCREEN=1
	-DROTATION=3
	-DWIDTH=128
	-DHEIGHT=64
	-DBACKLIGHT=-1
	-DMINBRIGHT=160

	;TFT_eSPI Setup
	-DUSER_SETUP_LOADED=1
	-DST7789_2_DRIVER=1
	-DTFT_RGB_ORDER=1
	-DTFT_WIDTH=135
	-DTFT_HEIGHT=240
	-DTFT_BACKLIGHT_ON=1
	-DTFT_CS=5
	-DTFT_DC=-1
	-DTFT_RST=-1
	-DTOUCH_CS=-1
	-DTFT_MOSI=15
	-DTFT_SCLK=13
	-DTFT_BL=-1
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=20000000
	-DSPI_READ_FREQUENCY=20000000
	-DSPI_TOUCH_FREQUENCY=2500000

	;SD Card Setup pins
	-DSDCARD_CS=-1
	-DSDCARD_SCK=0
	-DSDCARD_MISO=25
	-DSDCARD_MOSI=26

	;Default I2C port
	-DGROVE_SDA=32
	-DGROVE_SCL=33

	-DSPI_SCK_PIN=0
	-DSPI_MOSI_PIN=GROVE_SDA
	-DSPI_MISO_PIN=GROVE_SCL
	-DSPI_SS_PIN=26

lib_deps =
	${env.lib_deps}

/**********************************************************************
**  Function: loop
**  Main loop
**********************************************************************/
#if defined(HAS_SCREEN)
void loop() {
  #if defined(HAS_RTC)
    RTC_TimeTypeDef _time;
  #endif
  bool redraw = true;
  long clock_update=0;
  mainMenu.begin();

  // Interpreter must be ran in the loop() function, otherwise it breaks
  // called by 'stack canary watchpoint triggered (loopTask)'
#if !defined(LITE_VERSION)
  #if !defined(CORE) && !defined(CORE2)
    if(interpreter_start) {
      interpreter_start=false;
      interpreter();
      previousMillis = millis(); // ensure that will not dim screen when get back to menu
      //goto END;
    }
  #endif
#endif
  tft.fillRect(0,0,WIDTH,HEIGHT,bruceConfig.bgColor);
  bruceConfig.fromFile();

  while(1){
    if(interpreter_start) goto END;
    if (returnToMenu) {
      returnToMenu = false;
      tft.fillScreen(bruceConfig.bgColor); //fix any problem with the mainMenu screen when coming back from submenus or functions
      redraw=true;
    }

    if (redraw) {
      mainMenu.draw();
      clock_update=0; // forces clock drawing
      redraw = false;
      delay(REDRAW_DELAY);
    }

    handleSerialCommands();
#ifdef HAS_KEYBOARD
    checkShortcutPress();  // shortctus to quickly start apps without navigating the menus
#endif

    if (checkPrevPress()) {
      checkReboot();
      mainMenu.previous();
      redraw = true;
    }
    /* DW Btn to next item */
    if (checkNextPress()) {
      Serial.println("Check Next Press From Main.cpp");
      mainMenu.next();
      redraw = true;
    }

    /* Select and run function */
    if (checkSelPress()) {
      mainMenu.openMenuOptions();
      drawMainBorder(true);
      redraw=true;
    }
    // update battery and clock once every 30 seconds
    // it was added to avoid delays in btns readings from Core and improves overall performance
    if(millis()-clock_update>30000) {
      drawBatteryStatus();
      if (clock_set) {
        #if defined(HAS_RTC)
          _rtc.GetTime(&_time);
          setTftDisplay(12, 12, bruceConfig.priColor, 1, bruceConfig.bgColor);
          snprintf(timeStr, sizeof(timeStr), "%02d:%02d", _time.Hours, _time.Minutes);
          tft.print(timeStr);
        #else
          updateTimeStr(rtc.getTimeStruct());
          setTftDisplay(12, 12, bruceConfig.priColor, 1, bruceConfig.bgColor);
          tft.print(timeStr);
        #endif
      }
      else {
        setTftDisplay(12, 12, bruceConfig.priColor, 1, bruceConfig.bgColor);
        tft.print("BRUCE " + String(BRUCE_VERSION));
      }
      clock_update=millis();
    }
  }
  END:
  delay(1);
}
#else

// alternative loop function for headless boards
#include "modules/others/webInterface.h"

void loop() {
  setupSdCard();
  bruceConfig.fromFile();

  if(!wifiConnected) {
    Serial.println("wifiConnect");
    wifiConnectMenu(WIFI_AP);  // TODO: read mode from config file
  }
  Serial.println("startWebUi");
  startWebUi(true);  // MEMO: will quit when checkEscPress
}
#endif

**Comment by b1scuitdev** [comment]
@bmorcelli you can probably fix it can you help me?

**Comment by bmorcelli** [comment]
M5StickCPlus2 buttons have pull-up resistors, and when pressed the gpio is driven to LOW state..

In your implementation, when you press the button, you connect the GPIO to Vcc or to GND?

This mistake will make bruce work as Select btn is pressed all the time, is it that is happening to you?

If so, you need to change where the btns are read in interface.cpp to HIGH

https://github.com/pr3y/Bruce/blob/fd6a21ceb0e242a6640bfc6a59d1ed8c456aaecf/ports/m5stack-cplus2/interface.cpp#L76

https://github.com/pr3y/Bruce/blob/fd6a21ceb0e242a6640bfc6a59d1ed8c456aaecf/ports/m5stack-cplus2/interface.cpp#L93

https://github.com/pr3y/Bruce/blob/fd6a21ceb0e242a6640bfc6a59d1ed8c456aaecf/ports/m5stack-cplus2/interface.cpp#L111

https://github.com/pr3y/Bruce/blob/fd6a21ceb0e242a6640bfc6a59d1ed8c456aaecf/ports/m5stack-cplus2/interface.cpp#L128

https://github.com/pr3y/Bruce/blob/fd6a21ceb0e242a6640bfc6a59d1ed8c456aaecf/ports/m5stack-cplus2/interface.cpp#L146

https://github.com/pr3y/Bruce/blob/fd6a21ceb0e242a6640bfc6a59d1ed8c456aaecf/ports/m5stack-cplus2/interface.cpp#L425

https://github.com/pr3y/Bruce/blob/fd6a21ceb0e242a6640bfc6a59d1ed8c456aaecf/ports/m5stack-cplus2/interface.cpp#L428

**Comment by b1scuitdev** [comment]
Sadly this didn't work 
I connected one pin of the buttons to GND and the other pin to GPIO.


/*********************************************************************
** Function: checkNextPress
** location: mykeyboard.cpp
** Verifies Upper Btn to go to previous item
**********************************************************************/
bool checkNextPress(){ 
    if(digitalRead(DW_BTN)==HIGH) {
        if(wakeUpScreen()){
            delay(200);
            Serial.println("Down Button Pressed but wakeup screen boolean");
            return false;
        }   
        return true;
        Serial.println("Down Button Pressed");
    } 
    else return false;
}


also I tried setting to high this setting
	-DHAS_BTN=1
	-DSEL_BTN=14
	-DUP_BTN=27
	-DDW_BTN=12
	-DBTN_ACT=HIGH
	-DBTN_ALIAS='"M5"'

**Comment by b1scuitdev** [comment]
Okay i fixed it

    if (digitalRead(UP_BTN)==LOW)
    pinMode(UP_BTN, INPUT_PULLUP);   // Sets the power btn as an INPUT
    pinMode(SEL_BTN, INPUT_PULLUP);
    pinMode(DW_BTN, INPUT_PULLUP);
    	-DBTN_ACT=HIGH


these are worked!
