### ISSUE TITLE
Fix the screensaver

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#533]
When you start the device and display the screensaver, a message is displayed stating that the device does not support gif and blocks the screensaver. Please remove the message.
 By the way, add gif support for T-Embed cc1101.

**Comment by bmorcelli** [comment]
Already fixed in Beta

>By the way, add gif support for T-Embed cc1101.

It had beed removed from the program for now, it isn´t working at all.. maybe it came back later..
