### ISSUE TITLE
IOS Spam and WIFI clone + Deauth not working

### ISSUE THREAD

**Issue by Danyokkk** [BruceDevices/firmware#540]
Hi,

Today I was testing latest Beta on my stick, my internet is not that strong but Clone + Deauth did nothing I waited like for 10 minutes.

iOS Spam still not working, on iOS 18.1 not getting pop ups.

Problems with brightness I set my brightness to 50% but when I turn my stick it could be very dim or after bright.

Maybe it's only for me or I have problem with pn532 but my rfid module (pn532) not working on SPI.

That's all the glitches I have for the past 3 days.

**Comment by bmorcelli** [comment]
> iOS Spam still not working, on iOS 18.1 not getting pop ups.

IOS Patched their devices to not be victim of this prank.. so it probably won´t work

> Today I was testing latest Beta on my stick, my internet is not that strong but Clone + Deauth did nothing I waited like for 10 minutes.

Make sure your device isn´t connected to a 5Ghz network, these nets wont be affected

> Problems with brightness I set my brightness to 50% but when I turn my stick it could be very dim or after bright.

Can you please tell me the steps to reproduce?

**Comment by jakre1234** [comment]
Ios spam works fine with flipper zero though?
