### ISSUE TITLE
Small bug on brightnness setting on cardputer 

### ISSUE THREAD

**Issue by detcord0** [BruceDevices/firmware#541]
**describe the bug:**
i think it small bug.when go to brightness setting and select main menu  the screen just black, everything work except main menu choice.reboot solve the problem.

**Steps To Reproduce:**
go to config-brightness-select main menu
- Device used: 
Cardputer 
**Expected behavior:**

**Actual behavior:**
Screen turn black but navigation with keyboard are still working 

**Additional context / logs:**

**Comment by bmorcelli** [comment]
I'm on it
