### ISSUE TITLE
Share GPS of your Smartphone with Bruce over BT?.

### ISSUE THREAD

**Issue by ALoGeNo** [BruceDevices/firmware#545]
We have BT, and we have apps to share the smasrtphone GPS over BT, why can not use this feature?.

Just an idea, thanks guys your great work, cheers. (sorry I forget the label).

**Comment by rouing** [comment]
This isnt feasible because phones dont route the data from the GPS over bluetooth as a "native option"

This would require an application running on the phone to do this which would be a whole project by itself.
