### ISSUE TITLE
Bug with timer feature

### ISSUE THREAD

**Issue by detcord0** [BruceDevices/firmware#547]
**Describe the bug:**
There is a bug with timer feature.i tested the timer for 5 second after the countdown speaker are working but after that return to main menu this is when the bug begin the screen automaticly spam open file sd card and create new folder and dont stop or it does spam enter key

**Steps To Reproduce:**
Go to other-select timer -set timer- enter
- Device used: Cardputer 

**Expected behavior:**
Return to main menu/stop spaming

**Actual behavior:**

**Additional context / logs:**
I tested with bruce 1.8 and beta release before 1.8

**Comment by rennancockles** [comment]
Tested on multiple devices and could not reproduce the issue. Everything is working fine on cardputer and stickC plus 2

**Comment by detcord0** [comment]
Weird,It does give me bug.i am currently use bruce 1.8 and using launcher firmware.idk if it just me or somebody else have same problem but thank for the answer

**Comment by AlekseiGor** [comment]
Unfortunately, such behavior is not possible. The timer code is very simple and does not include any operations with the file system. If the defect is 100% reproducible, it would be great to attach a video of the process.

**Comment by bmorcelli** [comment]
It was happening after the timer runs out and play the speaker.. I could reproduce it in here.. it was a lib problem that sets GPIO_0 to output (instead of input) and then this gpio on cardputer makes select things (btn G0)

fixed here https://github.com/pr3y/Bruce/commit/5257fecc8dd88b1832f4341d168b0abf30c58484

**Comment by detcord0** [comment]
Thanks for answer .i have tested the latest beta release and  it solve the problem 
Note :thanks for all contributor hard work👍
