### ISSUE TITLE
Small bug report with sd card icon 

### ISSUE THREAD

**Issue by detcord0** [BruceDevices/firmware#548]
**Describe the bug:**
Sd card icon on left battery icon are offset after exit brucegotchi.the sd card icon are touch upper border line.

**Steps To Reproduce:**
Open brucegotchi-select main menu/exit brucegotchi feature

- Device used: 
Cardputer 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

**Comment by bmorcelli** [comment]
I just fixed it in here https://github.com/pr3y/Bruce/commit/1c0f58ea386494d76473de91d3077ab88c9db2ff

took so much time to find out what was happening, lol, to add one line to the code
