### ISSUE TITLE
Useful function for SubGhz signals

### ISSUE THREAD

**Issue by Teapot174** [BruceDevices/firmware#550]
Make a counter of the sent signals when sending a Sub signal. Let's say I have a .sub for brute force and I reproduce it, there are 1024 signals and for convenience it would be convenient to see on the screen what kind of signal is being sent, like:

![image](https://github.com/user-attachments/assets/b843f719-2f04-4086-a407-d10ccdc2fe13)

**Comment by bmorcelli** [comment]
added in https://github.com/pr3y/Bruce/pull/641
