### ISSUE TITLE
iOS Spam

### ISSUE THREAD

**Issue by xTyzen** [BruceDevices/firmware#551]
Good Afternoon ! I recently had a bug with iOS Spam in the BLE category. When I spam BLE for iOS devices it appears 1/2. So there are times when it doesn't work, but times when it does. When it spams, it only spams one device. So there is always a device visible on my iPhone. It only appears once every time. And not several times. Thank you for your understanding! I am writing this message to help you improve BLE and above all to help you find out where the problem is. And make it less frustrating for other users. Good day !

**Comment by dghlkxyvdyxj** [comment]
apple patched ios popup spamming on ios 18

**Comment by jakre1234** [comment]
Not really, the ios spam and android spam works perfectly with flipper zero
