### ISSUE TITLE
RF send signal not work for m5stickcplus 1.1

### ISSUE THREAD

**Issue by hunt3rbb666NotFound** [BruceDevices/firmware#556]
Hi, thanks for what you are doing. I have a question, I saved the raw rf signal of my key to test the sending of the signal with the m5stickc plus 1.1 device with cc1101, sending the raw signal from the display seems to work but in reality it does not work at least for me. Have you by any chance done the tests to verify this problem? I follow you a lot and for this reason I purchased and am waiting for a Lyligo T Embed CC1101 to install Bruce! So I would not like to have the same problem..can you help me understand? I tried 1.8 and beta version. Thanks again!

**Comment by rouing** [comment]
Are you using something that has a rolling code? What kind of key? 

Also, do you have an RTL-SDR of some sort to monitor for confirmation of the tx?

**Comment by hunt3rbb666NotFound** [comment]
Thanks for the reply. It does not use rolling code, the car key is from an old Nissan that runs on frequency 433.8x. Unfortunately I do not have RTL-SDR to confirm tx.

**Comment by rouing** [comment]
> Thanks for the reply. It does not use rolling code, the car key is from an old Nissan that runs on frequency 433.8x. Unfortunately I do not have RTL-SDR to confirm tx.

Are you 100% sure the Nissan key is not a rolling code?

**Comment by hunt3rbb666NotFound** [comment]
I did some more in-depth research and you're right, use rolling code. But shouldn't he do it once anyway?

**Comment by rouing** [comment]
Make sure to capture it away from your car first so that the car doesnt pick up the signal. Im still not sure if thats all thats at play here

**Comment by hunt3rbb666NotFound** [comment]
Yes, I picked up the signal at home. :/
