### ISSUE TITLE
bruce on esp32 wroom

### ISSUE THREAD

**Issue by Manulatech** [BruceDevices/firmware#558]
I purchased an esp32 wroom and a 2.8TFT- ILI9341 IC
I would like to install Bruce on it, how do I do it and what are the connections to make?

**Comment by rouing** [comment]
If you need assistance with install I recommend joining the discord
https://discord.gg/WJ9XF9czVT

**Comment by bmorcelli** [comment]
https://discord.com/channels/1264994142769909854/1309534054085038100
