### ISSUE TITLE
Diffrecne between launcher and normal 

### ISSUE THREAD

**Issue by Grzybekrk** [BruceDevices/firmware#564]
Hi I can see launcher has much less option donyou know why? Example no bad ble or pwnd

**Comment by rouing** [comment]
![image](https://github.com/user-attachments/assets/f2169cb1-ac34-4b91-9329-2df6b223c42b)

**Comment by bmorcelli** [comment]
Full Bruce uses at least 3.3mb of flash memory... Launcher uses almost 1.5mb... so we need to cut some features in order to have it usable with Launcher in devices that have only 4mb of flash memory...
