### ISSUE TITLE
Esp32 CYD-2432S028 BADUSB Connection

### ISSUE THREAD

**Issue by BeqaMiqa** [BruceDevices/firmware#573]
**Describe the bug:**

The badusb functionality doesn't seem to work for esp32 CYD-2432S028

**Steps To Reproduce:**

- Device used: 

I have connected the cyd tx to ch3929 Rx pin, GND to GND Rx to tx, I have even tested  the ch9329 module separately on a different esp and it worked fine

**Expected behavior:**

It should start executing the example Bruce script that was given in the repo

**Actual behavior:**

It flashes ch9329 -> USB but nothing happens and when I select back it says module not found 

**Additional context / logs:**

![20241217_163210.jpg](https://github.com/user-attachments/assets/1eef1a38-660c-4fda-b5f9-c2709921ca01)

![20241217_163150.jpg](https://github.com/user-attachments/assets/526e1a27-d2d9-44c3-b6af-83e667954691)

**Comment by bmorcelli** [comment]
Pis are wrong, you need to connect to 22 and 27

https://github.com/pr3y/Bruce/blob/7ba77cad1057cf3e38908caffe300b339bf03443/ports/CYD-2432S028/platformio.ini#L60-L61

https://github.com/pr3y/Bruce/blob/7ba77cad1057cf3e38908caffe300b339bf03443/ports/CYD-2432S028/platformio.ini#L158-L159

**Comment by BeqaMiqa** [comment]
If the baudrate is set to 115200 we would need a level shifter because the CH9329 can not communicate 115200 at 3.3 v it needs 5v, but in the code I saw that we are using the ch9329 default baudrate which is 9600, maybe this is written for other modules other than the cyd?

**Comment by bmorcelli** [comment]
> but in the code I saw that we are using the ch9329 default baudrate which is 9600, maybe this is written for other modules other than the cyd?

It was written and fully tested on M5StickCs and M5Core2 devices..  Baud Rate is 9600 (Default CH9329), try connecting 5V to Vcc (3.3V), it needs the voltage reference to work, or you can extract a 5V pin from CYD Usb cable or from the voltage regulator.

**Comment by BeqaMiqa** [comment]
> Pis are wrong, you need to connect to 22 and 27
> 
> https://github.com/pr3y/Bruce/blob/7ba77cad1057cf3e38908caffe300b339bf03443/ports/CYD-2432S028/platformio.ini#L60-L61
> 
> https://github.com/pr3y/Bruce/blob/7ba77cad1057cf3e38908caffe300b339bf03443/ports/CYD-2432S028/platformio.ini#L158-L159
> 
> 

Ok at first it didn't work after trying and testing, I reflashed the CYD and after connecting the pins like so:

CH9329        CYD
   GND     ->   GND
   TX        ->     22
   RX        ->     27

It worked!

It's just that if you exit the BADUSB page you need to unplug the ch9329 and plug it back in.

Also I didn't know there was a Rick roll Easter egg, I got got :D

Thanks for the help.

**Comment by bmorcelli** [comment]
Haha Ricky is awesome! Lol

Glad it worked
