### ISSUE TITLE
STM32F030 support

### ISSUE THREAD

**Issue by cinouw** [BruceDevices/firmware#575]
Hi Bruce team 

recently i bought a stm32f030 io expander to use it in my own project and wile i was reading the product discription i noticed that the expantion module is also capble of 6 GPIO pins.

I think it would be a greate alterrnative to SD card sniffer adapter and a cleaner solution

If would like to add support for the module i have the module I can help with debugging any time 

thanks

**Comment by bmorcelli** [comment]
These modules are driven by I2C communication, so you need to send commands using 2 wires to it to drive the pins on and off.. and you can read them too, by commanding it through I2C.. 

you can try to emulate an SPI communication driving these pins on/off and reading them, but it is quite hard and slow.. and you can loos a lot of data throughout this interface.

so, even being remotely possible, it probably won't be done.
