### ISSUE TITLE
Battery indicator CYD

### ISSUE THREAD

**Issue by BeqaMiqa** [BruceDevices/firmware#577]
Does the battery level indicator work for CYD 2432s028? If it does what are the pin config?

**Comment by bmorcelli** [comment]
No it doesn't, CYD doesn't have dedicated pin for battery reading unfortunately

**Comment by Grzybekrk** [comment]
If we use sd sniffer too??

**Comment by bmorcelli** [comment]
We can't read battery natively on CYD
