### ISSUE TITLE
Error when using the 125k Hz reading option in version 1.8

### ISSUE THREAD

**Issue by pietrohoff** [BruceDevices/firmware#582]
**Describe the bug:**
In version 1.8, after using the 125k Hz reading option, the system no longer detects the RFID module. It displays the following error message:

> RFID module not found!

**Steps To Reproduce:**

1. Open Bruce version 1.8.
2. Set the system to operate at 125k Hz.
3. Perform a reading with this configuration.
4. Notice that after the operation, the system displays the error message and the RFID module is no longer detected.
- **Device used**: RFID module (specific model unknown).

**Expected behavior:**
N/A

**Actual behavior:**
The system fails to detect the RFID module and shows the error message "RFID module not found!" after using the 125k Hz option.

**Additional context / logs:**
If additional logs or testing are required, please let me know.

**Comment by bmorcelli** [comment]
125kHz works with RDM6300 to read and save tags, using the following schematics: https://github.com/pr3y/Bruce/pull/182#issuecomment-2287692412

M5 RFID and PN532 works with 13Mhz tags.
