### ISSUE TITLE
GIF Feature

### ISSUE THREAD

**Issue by CYD-USER** [BruceDevices/firmware#584]
In the releases there is wrtten that you  can play gifs but it doenst work for me onlyblank screen 

I using the cyd 2usb with m5launcher launcher verson 1.8
opening in others sd card and then selecting the File going to view file 

I thought that it will play my gif an then i can exit again
 blank screen and also cant exit 

ps the gifs is over 10 mbs could this be the problen

**Comment by bmorcelli** [comment]
It was available for Cardputer, but it isn't working anymore, unfortunately 

10mb is way too big too, it would work with small files

**Comment by CYD-USER** [comment]
ah ok do pictures work then or mp4s
