### ISSUE TITLE
[T-Embed-CC1101] Battery indicator does not rise above 50%

### ISSUE THREAD

**Issue by shnmorimoto** [BruceDevices/firmware#585]
**Describe the bug:**

Even after charging, the battery indicator does not rise above 50%

![IMG_0151](https://github.com/user-attachments/assets/fd58f2f0-6cbb-4d5a-b63d-64db38dfa7a4)

**Steps To Reproduce:**

- Device used: T-Embed-CC1101
- Beta Release 50d0781（There was no issue with 1.8.）

**Expected behavior:**

Charged to 100%

**Actual behavior:**

Charging seems to stop at around 50%
It may just be a display issue, but I don't know...

**Additional context / logs:**

**Comment by EnygmaINC** [comment]
Same. Above ~40% for me.

**Comment by shnmorimoto** [comment]
Even with factory firmware, charging stops halfway through.

I'm not sure, but the full capacity is set to 3000. Is that correct?

It should be 1300mAh?

![IMG_0152](https://github.com/user-attachments/assets/240473ad-9def-4f78-be5a-648deae2fb40)

**Comment by shnmorimoto** [comment]
It displayed normally after I flashed the firmware several times.
I guess it was a problem with my device.
