### ISSUE TITLE
Random JPG boot for CYD not working

### ISSUE THREAD

**Issue by Grzybekrk** [BruceDevices/firmware#592]
Can you please advise if random boot JPG works on CYD ? I tried but its black tried different format size and still cannot figure out how to change it

**Comment by bmorcelli** [comment]
I works when you install the full version of Bruce.. for Launcher version it is not available yet.. 

you must save a file named "boot.jpg" into the root of SD Card, resize the image to the maximum size of the display (320x240px) or lower (240:135px)
