### ISSUE TITLE
Bruce ver 1.1.0.  m5stickc plus 2 the IR Tx pin will be forgotten

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#60]
The ui color setting wasn't being saved on ver 1.0.2 but in the new version it'll be saved for some time and will get forgotten. There is a new issue that wasn't in the older version which is the firmware won't save the saved IR_TX pin. ( I set it to default on the m5stickc plus 2.)

**Comment by bmorcelli** [comment]
Wull be fixed in https://github.com/pr3y/Bruce/pull/71
