### ISSUE TITLE
FM functions are not working on Cardputer with CJMCU-4713

### ISSUE THREAD

**Issue by ghost** [BruceDevices/firmware#605]
**Describe the bug:**
After correctly connecting the module and choosing any FM functions, firmware outputs "Cannot find radio".

**Steps To Reproduce:**
1. Connect CJMCU-4713 to grove pins on Cardputer as described in this repo.
2. Short RST and GND to enable module.
3. Go into FM functions and select any of them.
4. Error "Cannot find radio".

**Device used:**
M5 Cardputer
FM module CJMCU-4713: https://sl.aliexpress.ru/p?key=Xi0sGk9

**Expected behavior:**
FM functions working

**Actual behavior:**
FM functions are not working

**Additional context / logs:**
Connections are soldered and tested.

The thing in question:
![fm](https://github.com/user-attachments/assets/2c6e98e7-e17e-4df3-bae0-404dca1738c8)

**Comment by bmorcelli** [comment]
Try changing the switch beside the grove to 5VOUT position (towards the grove)

**Comment by ghost** [comment]
> Try changing the switch beside the grove to 5VOUT position (towards the grove)

It was already in that position. Also tried in 5VIN position, didn't work.

**Comment by ghost** [comment]
Update: it works on M5 Stick Plus2. Connections stayed the same, I just plugged grove cable in Stick.

**Comment by Grzybekrk** [comment]
Is this works on cardputer ??

**Comment by romacoma11** [comment]
> Update: it works on M5 Stick Plus2. Connections stayed the same, I just plugged grove cable in Stick.
how could you connect this to a stick

**Comment by romacoma11** [comment]
how could you connect this to the stick

**Comment by romacoma11** [comment]
how could you connect this to the stick

**Comment by romacoma11** [comment]
> Update: it works on M5 Stick Plus2. Connections stayed the same, I just plugged grove cable in Stick.

how did you connect it to a stick
