### ISSUE TITLE
Backlight on button area

### ISSUE THREAD

**Issue by ghost** [BruceDevices/firmware#606]
Hello, as far as I know, the t-embed has a built-in backlight in the button area. By default, there is a function in the firmware to turn on and adjust this backlight, do you plan to do this in the Bruce firmware as well? I think many people would like to see this feature in the new update.

**Comment by bmorcelli** [comment]
It is being developed here https://github.com/pr3y/Bruce/pull/563

**Comment by ghost** [comment]
There's a lot of information there, and it's not very clear how to turn on the backlight.

**Comment by ghost** [comment]
Can you provide me with something like a guide on how to do this?

**Comment by bmorcelli** [comment]
you wait ;)

**Comment by ghost** [comment]
pls

**Comment by rouing** [comment]
> pls

Its currently being developed. The feature has not been released yet. Check the linked PR to see why:

              Pending #571 merge to fix up the flags

_Originally posted by @rouing in https://github.com/pr3y/Bruce/issues/563#issuecomment-2556722250_

**Comment by bmorcelli** [comment]
Available now on Beta
