### ISSUE TITLE
Add BLE Keyboard and Custom QR Feature

### ISSUE THREAD

**Issue by nikyy2** [BruceDevices/firmware#611]
# Hey, I would like to suggest a new feature in BLE. It would be great if you could add a BLE keyboard that connect to device (Iphone, Android, Window,...) so users can use it as a Bluetooth Keyboard. Also the BLE keyboard UI will be the same as keyboard UI currently used when entering passwords for Wi-Fi or entering custom QR.  

Using Bruce as a Bluetooth keyboard !!!

# It would be cool to have a custom QR code feature that use litteFS. Here’s the idea:  
- Users to upload saved text files (e.g., `.txt`) to LittleFS.  
- In the QR code section, provide an option to choose one of the uploaded `.txt` files to generate a QR code.  
- For instance, a file containing `https://bruce.computer/` could be selected and converted into a QR code.  

This would help sharing links, social media accounts, much easier and faster without needing to retype them every time.  

**Best regards,**  
**nikyy2**

**Comment by dghlkxyvdyxj** [comment]
it would maybe not work for the stick but for cardputer would be nice

**Comment by bmorcelli** [comment]
> It would be great if you could add a BLE keyboard that connect to device (Iphone, Android, Window,...) so users can use it as a Bluetooth Keyboard.

It is available for Cardputer and T-Deck, in other devices would be way too hard to type

>It would be cool to have a custom QR code feature that use litteFS.

It is available on Beta, you download the file bruce.conf, and add the QR codes you want.
