### ISSUE TITLE
BLE spam is very bad

### ISSUE THREAD

**Issue by ghost** [BruceDevices/firmware#617]
The ble spam function works very poorly even compared to nemo, not to mention the flipper. iOS and android spam send one connection request per minute, and that's the maximum it could. Are you planning to fix this issue?

**Comment by bmorcelli** [comment]
It will be completely removed

**Comment by ghost** [comment]
Will this feature be removed or will it be fixed for the problem?

**Comment by bmorcelli** [comment]
> It will be completely removed 

.

**Comment by Viarety** [comment]
Пиздец
