### ISSUE TITLE
M5stick c plus 2 with digispark attiny85

### ISSUE THREAD

**Issue by TomasBrychta** [BruceDevices/firmware#623]
Its possible to connect m5stick c plus 2 worh digispark attiny85 for bad usb? And is bruce ready to this setup? Thanks

**Comment by bmorcelli** [comment]
To do that you will need to make digispark comunicate with the ESP32 with some sort or communication (UART, I2C or somethin) to send the strings to send through USB.. I (personally) couldn't do that.. but if you have an idea to make the digispark firmware and make the bruce code to send the messages, maybe you can do it..

but for now, it is not available
