### ISSUE TITLE
Switch to LVGL

### ISSUE THREAD

**Issue by b1scuitdev** [BruceDevices/firmware#631]
Recommendation: Switch to lvgl it looks way better and easier

**Comment by rouing** [comment]
This has been discussed before and is still sort of under discussion still. Originally, Bruce did use LVGL but there was a problem with Animations and overall lag. Its still not a "No" and may even be a probably (in the future) but there is some serious refactoring that needs to go on first.

**Comment by bmorcelli** [comment]
impossible
