### ISSUE TITLE
Lt5534

### ISSUE THREAD

**Issue by TomasBrychta** [BruceDevices/firmware#634]
Hi, what do you think about implement this module in future to Bruce? 

https://www.analog.com/media/en/technical-documentation/user-guides/dc748a.pdf

Its possible to order only 1pcs chip LT5534 without board for only 12$ so it seems like good add-on to this project if somebody makes his own Bruce pcb.

**Comment by eadmaster** [comment]
It only **detects** rf signals, it cannot record or replay them.

It seems to output a simple analog value that can be read and shown via a js script:

https://forum.arduino.cc/t/rf-power-detector-with-lt5534-phone-proximity-detector/596768

(No need to have specific support for this in Bruce)
