### ISSUE TITLE
Feature Request #2

### ISSUE THREAD

**Issue by dghlkxyvdyxj** [BruceDevices/firmware#636]
1. BLE Spammer (spams random devices with random names and devices types) rickroll or random funny names
2. Copy & Send Smart Home Signals (for example turning off the lights, switching colors or turning on radio sockets) if thats possible
3. Passcode & Fingerprint lock the device (fingerprint module: https://shop.m5stack.com/products/finger-sensor-unit) Usefull if you dont want someone else use your device
4. Flashlight (Flashlight module https://shop.m5stack.com/products/flashlight-unit)

**Comment by rouing** [comment]
There already is BLE Spamming
The "Smart Home Signals" you can (try to) do with the "RAW" SubGhz so long as its something like Z-Wave or SubGHz Protocols. 2.4GHz Protocols like Zigbee, Thread, etc... are out of the scope of this project currently.
Passcode locking can potentially be added but is not a priority. Fingerprint is out of the scope of this project.
The "Flashlight" thing is really out of the scope of what this project is for. There is LED Support added and being improved upon for the devices we support that have built in RGB LED's.
