### ISSUE TITLE
TV-B Gone not working v1.1.0

### ISSUE THREAD

**Issue by Rol3oT** [BruceDevices/firmware#65]
Cardputer Bruce version 1.1.0 when going to the TV-B Gone menu, it opens the menu letting you select between regions, except without any inputs it jumps to "please wait" screen with loading bar and I cant get out of that screen unless I reset cardputer. It doesn't seem to send any IR signals either as TV wouldnt turn off (this same tv would turn off with NEMO tv-b gone version)

**Comment by eadmaster** [comment]
fixed [here in my fork](https://github.com/eadmaster/Bruce), only for the NEC protocol atm.

Menu navigation still seems to have bugs and goes into infinite loops.

**Comment by bmorcelli** [comment]
Wull be fixed in https://github.com/pr3y/Bruce/pull/71
