### ISSUE TITLE
Problème RF Spectrum

### ISSUE THREAD

**Issue by ghost** [BruceDevices/firmware#68]
Bonjour,
J'ai un rf433r et lorsque j'essaie le "RF" (Spectrum) sur m5 stick c plus 2 cela ne fonctionne pas.
Ça redémarre le programme Bruce.

**Comment by bmorcelli** [comment]
Salut, j'essaie de résoudre ce problème en ce moment... je soupçonne qu'il démarre les mauvaises broches... donc j'espère envoyer un patch pour cela bientôt

Désolé pour la mauvaise traduction de Google Translate

**Comment by ghost** [comment]
D'accord merci :)
(Ça à bien traduit)

**Comment by bmorcelli** [comment]
Found the bug...

In the last update of arduino framework for esp32 the parameters of the function rmt_config() have changed, and the Macro ESP_ERROR_CHECK() is making it reboot after the error message on Serial...

You'll find the call for this function on line 39 of src/rf.cpp file

Now we can search for a way to fix it..

**Comment by bmorcelli** [comment]
Wull be fixed in https://github.com/pr3y/Bruce/pull/71
