### ISSUE TITLE
The new version of the firmware won't remember the "IR TX Pin" setting. 

### ISSUE THREAD

**Issue by Z-SHOCK-E** [BruceDevices/firmware#79]
I flashed the new firmware to the m5stickc plus 2 and used the tv-b-gone function but it didn't work. So I changed the ir tx pin setting to default and then it worked but, after some time I rebooted it and it was again not working.

**Comment by bmorcelli** [comment]
Hello @Z-SHOCK-E .. thanks for reporting..

there were a missing default global to be saved on the EEPROM, and it was causing the settings to reset after reboot.

I'm on in right now

**Comment by bmorcelli** [comment]
Feature added in this PR https://github.com/pr3y/Bruce/pull/80

Will be available soon
