### ISSUE TITLE
Idea SD Card Show/Hide

### ISSUE THREAD

**Issue by ghost** [BruceDevices/firmware#86]
Good morning,
Possible to have a logo of the SD card in the menu of the "Bruce" software once inserted and once removed in this case no more logo?

Thank you

**Comment by Ademolght** [comment]
Why?

**Comment by ghost** [comment]
> Why?

For me, it's something more.
an indication.

**Comment by Ademolght** [comment]
Ok

**Comment by bmorcelli** [comment]
Added in https://github.com/pr3y/Bruce/pull/93

Will be available in the next update
